### ISSUE TITLE
Optional "id" property

### ISSUE THREAD

**Issue by Planche95** [RicoSuter/NJsonSchema#1007]
Example Json Schema:

```
{
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "name": { "type": "string" },
    "email": { "type": "string" },
    "address": { "type": "string" }
  },
  "required": [ "name", "email" ]
}
```

I try to validate empty json `{ }`

Errors:
![image](https://user-images.githubusercontent.com/18653765/59342127-6e85df00-8d09-11e9-9b57-d524271b4858.png)

Why am I getting this **"StringExpected: #/id"**? When I change the name of a property this error not occur.

**Comment by Planche95** [comment]
? :)

**Comment by RicoSuter** [comment]
Can you add the code you’re calling to validate? Are you using the string based one?

**Comment by Planche95** [comment]
```
public async Task ValidateAsync<T>(T model)
{
    JsonSchema schema = await GetSchemaAsync<T>();
    JObject jsonObject= GetJObject(model);

    var errors = schema.Validate(jsonObject.ToString());

    if (errors.Count > 0)
        throw new ModelValidationException($"Error messages:\n{string.Join('\n', errors)}");
}
```
GetSchemaAsync() gets a proper schema.
GetJObject() convert my model to JObject.

**Comment by RicoSuter** [comment]
> GetJObject() convert my model to JObject.

I think the problem is in your GetJObject() method as it might convert "id" to something else - there are serializer options to change this behavior
