### ISSUE TITLE
Inheritance problem

### ISSUE THREAD

**Issue by mutzl** [RicoSuter/NJsonSchema#1008]
I was following the [inheritance](https://github.com/RicoSuter/NJsonSchema/wiki/Inheritance) guide.

dotnet core 2.1
Swashbuckle.AspNetCore **4**.0.1
NJsonSchema 10.0.18

    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Microsoft.AspNetCore.Cors;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Newtonsoft.Json;
    using NJsonSchema.Converters;

    namespace WebApi.Controllers
    {
        [Route("api/[controller]")]
        [ApiController]
        [Produces("application/json")]
        [EnableCors("AllowAllHeaders")]
        public class DemoController : ControllerBase
        {

            [HttpGet("array")]
            [ProducesResponseType(StatusCodes.Status200OK)]
            public ActionResult<ContainerWithArray> GetContainerWithArray()
            {
                return new ContainerWithArray
                {
                    Animals = new Animal[]
                    {
                                new Cat { Foo = 1, AnotherBar = "cat 1", },
                                new Dog { Foo = 2, Bar = "dog 2", },
                                new Cat { Foo = 3, AnotherBar = "cat 3", },
                    }
                };
            }

            [HttpGet("object")]
            [ProducesResponseType(StatusCodes.Status200OK)]
            public ActionResult<ContainerWithObject> GetContainerWithObject()
            {
                return new ContainerWithObject
                {
                    Animal = new Cat { Foo = 1, AnotherBar = "cat 1", }
                };
            }

        }

        public class ContainerWithArray
        {
            public IEnumerable<Animal> Animals { get; set; }
        }

        public class ContainerWithObject
        {
            public Animal Animal { get; set; }
        }

        [JsonConverter(typeof(JsonInheritanceConverter), "discriminator")]
        [KnownType(typeof(Dog))]
        [KnownType(typeof(Cat))]
        public class Animal
        {
            public int Foo { get; set; }
        }

        public class Dog : Animal
        {
            public string Bar { get; set; }
        }

        public class Cat : Animal
        {
            public string AnotherBar { get; set; }
        }

    }

        [JsonConverter(typeof(JsonInheritanceConverter), "discriminator")]
        [KnownType(typeof(Dog))]
        [KnownType(typeof(Cat))]
        public class Animal
        {
            public int Foo { get; set; }
        }

        public class Dog : Animal
        {
            public string Bar { get; set; }
        }

        public class Cat : Animal
        {
            public string AnotherBar { get; set; }
        }

    }

The response looks correct, the Json objects include the discriminator field.

    {
        "animals": [
        {
            "anotherBar": "cat 1",
            "foo": 1,
            "discriminator": "Cat"
        },
        {
            "bar": "dog 2",
            "foo": 2,
            "discriminator": "Dog"
        },
        {
            "anotherBar": "cat 3",
            "foo": 3,
            "discriminator": "Cat"
        }
        ]
    }

Though the generated swagger.json does not mention the Cat or Dog class.

    {
        "swagger": "2.0",
        "info": {},
        "paths": {
            "/api/Demo/array": {
                "get": {
                    "tags": [
                        "Demo"
                    ],
                    "operationId": "GetContainerWithArray",
                    "consumes": [],
                    "produces": [
                        "application/json"
                    ],
                    "parameters": [],
                    "responses": {
                        "200": {
                            "description": "Success",
                            "schema": {
                                "$ref": "#/definitions/ContainerWithArray"
                            }
                        }
                    }
                }
            },
            "/api/Demo/object": {
                "get": {
                    "tags": [
                        "Demo"
                    ],
                    "operationId": "GetContainerWithObject",
                    "consumes": [],
                    "produces": [
                        "application/json"
                    ],
                    "parameters": [],
                    "responses": {
                        "200": {
                            "description": "Success",
                            "schema": {
                                "$ref": "#/definitions/ContainerWithObject"
                            }
                        }
                    }
                }
            }
        },
        "definitions": {
            "ContainerWithArray": {
                "type": "object",
                "properties": {
                    "animals": {
                        "uniqueItems": false,
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/Animal"
                        }
                    }
                }
            },
            "Animal": {
                "type": "object",
                "properties": {
                    "foo": {
                        "format": "int32",
                        "type": "integer"
                    }
                }
            },
            "ContainerWithObject": {
                "type": "object",
                "properties": {
                    "animal": {
                        "$ref": "#/definitions/Animal"
                    }
                }
            }
        }
    }

Therefore also the TypeScript code generation using NSwagStudio is not aware of the inherited classes.

What am I missing?

**Comment by RicoSuter** [comment]
This only works with nswag as spec generator (nswag.aspnetcore) not with swashbuckle. I dont know how to describe inheritance there...

**Comment by mutzl** [comment]
I missed that. 
Changing now from Swashbuckle to NSwag...
