### ISSUE TITLE
Defining Example objects

### ISSUE THREAD

**Issue by vdecristofaro** [RicoSuter/NJsonSchema#1010]
Is there any way to generate example objects of operation responses, as foreseen by the [specification](http://swagger.io/specification/#exampleObject)?

From @rsuter: **Solved**: Read this blog: https://blog.rsuter.com/nswag-tutorial-implement-a-custom-operation-processor-to-define-redoc-code-samples/

**Update:** See https://github.com/RicoSuter/NJsonSchema/wiki/XML-Documentation#define-examples

**Task:** Use GenerateExample() for request response, params etc

**Comment by RicoSuter** [comment]
Move to NJsonSchema

**Comment by RicoSuter** [comment]
See https://github.com/RicoSuter/NJsonSchema/wiki/XML-Documentation#define-examples

**Comment by RicoSuter** [comment]
Task: Use GenerateExample() for responses/requests

**Comment by davidkeaveny** [comment]
In .NET Core 2.2, how can we programatically add example response data? Previous versions of `SwaggerResponse` had an `Examples` property, and I was able to write an `IOperationProcessor` that would populate that property based on data generated at build time. From your above link to the NJsonSchema wiki, it will add any `<example />` XMLDOC comments, but to be honest, creating example code in XML comments does not scale well, and worse, doesn't give compile time errors when the schema changes and you forget to update the documentation.

In OpenAPI schema, the examples are children of the media type (when using $ref to reference the schema) - is that easily supported in NSwag/NSwagSchema?

**Comment by RicoSuter** [comment]
Have you tried the example xml docs?

**Comment by davidkeaveny** [comment]
Ah, I figured out what I was doing wrong - I was referencing the wrong NSwag libraries in my `IOperationProcessor` - the NuGet package descriptions give no clues, but the NSwag readme.md does give adequate information to work out which ones I wanted. Now, if only the Swagger UI could handle the examples in OpenAPI format a bit better...

Regarding the use of the `<example />` XMLDOC comments, I didn't try it and it wouldn't meet my requirements, really - the main issue is keeping the example in sync with the model (both addition/removal of fields, and type-safety of data), which is much easier to do with programatically generated code.

My solution is a little long to include here, so I'll try to write it up in a wiki and post the link, it might be useful for others in the same situation.

**Comment by Leon99** [comment]
@davidkeaveny have you managed to document your solution?
I'm missing Swashbuckle's way to define the examples programmatically, would appreciate if someone could share a solution using NSwag.

**Comment by RicoSuter** [comment]
@leon99 did you check out this blog post: https://blog.rsuter.com/nswag-tutorial-implement-a-custom-operation-processor-to-define-redoc-code-samples/

**Comment by Leon99** [comment]
Thanks @RicoSuter, I did check that post. It's a good start, but it only tells half of the story since it suggests specifying the source code as a string, while I, just like @davidkeaveny, am looking for a way to pass an object and have it appear as an example of the model in the doc. That, I guess, would involve generating the code by using reflection over the provided object. Swashbuckle allows that out of the box.

**Comment by baltika10** [comment]
@davidkeaveny 
> My solution is a little long to include here, so I'll try to write it up in a wiki and post the link, it might be useful for others in the same situation.

As I understand, you didn't manage to write some instructions, but maybe you can just share some info regarding your solution?

**Comment by davidkeaveny** [comment]
Sorry it's been so long for me to post on this - I've now moved on to a .NET Core 3.1 project, and to be honest, I find it much easier now to use the `<example>` XMLDOC field to provide sample data. For instance, the following DTO:

```
/// <summary>
/// A calendar event that should be rendered as part of a leave calendar.
/// </summary>
public class CalendarEvent
{
    /// <summary>
    /// The date of the calendar event, expressed as an offset from January 1st; so 0 would represent January 1st, and 364 would represent December 31st in a non-leap year.
    /// </summary>
    /// <example>0</example>
    public int CalDate { get; set; }

    /// <summary>
    /// The background colour that should be used when rendering the event, expressed as the integer representation of the RGB hexadecimal colour codes.
    /// </summary>
    /// <example>3058159</example>
    public int CalBackColour { get; set; }

    /// <summary>
    /// The foreground colour that should be used when rendering the event; 0 represents black and -1 represents white.
    /// </summary>
    /// <example>-1</example>
    public int CalForeColour { get; set; }

    /// <summary>
    /// The type of the calendar event.
    /// </summary>
    /// <example>Public Holiday</example>
    public string CalType { get; set; }

    /// <summary>
    /// The text that should be displayed in a tooltip when rendering the event.
    /// </summary>
    /// <example>New Year's Day</example>
    public string CalTooltipText { get; set; }
}
```
then gets rendered (here using ReDoc) as:

![image](https://user-images.githubusercontent.com/1229960/96060242-b4dde600-0edb-11eb-9048-f66e5a6a3279.png)

It works nicely with the multiple response types; its only problem so far is that in my case, the 400 and 500 responses return the same object, which means they get the same example; but that's really a very minor complaint.

The approach I used of creating my own attribute (similar to `ProducesResponse`) and then my own operation processor to handle that attribute now feels a lot like overkill.

I am really happy with the way NSwag is working for me, so two huge thumbs-up from me to @RicoSuter

**Comment by vaclavnovotny** [comment]
@Leon99 @baltika10 @davidkeaveny I have solved this and put together a solution to programmatically define response examples, check it out [NSwag.Examples](https://github.com/vaclavnovotny/NSwag.Examples)
