### ISSUE TITLE
Use System.Text.Json in JSON Schema generator

### ISSUE THREAD

**Issue by RicoSuter** [RicoSuter/NJsonSchema#1014]
Open questions: 

- **How can we reflect over the used contracts (replacement for Newtonsoft.Json's contract resolver)?**
    - => currently this feature is completely missing in System.Text.Json and we need to use reflection and manually implement the same rules in the schema generator (suboptimal)
- NJS might reference System.Text.Json and Newtonsoft.Json at the same time to support both libraries depending on a setting
    - E.g. you either set a Newtonsoft.Json contract resolver/serializer settings or System.Text.Json settings/contract metadata
- System.Text.Json is only .NET Standard 2.0 but NJS supports .NET Standard 1.0 and .NET 4.0
    - Lots of #if and System.Text.Json support will not be active in all target frameworks (will throw NotSupportedExceptions otherwise)

Current implementation (NJS 10.1.15+, NSwag v13.5.0+): 

- [x] Currently NJS uses reflection only to support System.Text.Json (no direct dependency)
- [x] Support for JsonStringEnumConverter
- [x] Support for JsonPropertyNameAttribute
- [x] Support for (custom) PropertyNamingPolicy
- [ ] Json.NET attributes should be ignored when using System.Text.Json (in the custom SystemTextJsonContractResolver), https://github.com/RicoSuter/NSwag/issues/2762
- [ ] Currently not supported features: Probably some of the new attributes are currently not supported: https://github.com/RicoSuter/NJsonSchema/issues/1013

See https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/SystemTextJsonUtilities.cs

**Comment by steveharter** [comment]
For 3.0 there are no public APIs to return the metadata. These were considered but considered out of scope for this release because we are focusing on a minimum viable product for mainstream scenarios.

I'd like to expose the metadata, which would also be required for a new type of "converter" that I would like to add. The new converter would handle some scenarios the existing one can't.

**Comment by RicoSuter** [comment]
Ok. As long as metadata is not exposed by System.Text.Json we cannot support this new library in NJsonSchema (JSON Schema generation) and NSwag (Swagger/OpenAPI) - so this might be a huge blocker for people who want to use the new serializer in ASP.NET Core AND OpenAPI. 

**The solution for now is to use System.Text.Json for serialization and add NSwag with a Newtonsoft.Json contract resolver which resembles the System.Text.Json serializer behavior...**

**Comment by jemiller0** [comment]
I thought System.Text.Json was .NET Standard 2.1, not 2.0... If so, it wouldn't run on .NET Framework at all.

**Comment by RicoSuter** [comment]
It seems to support .net standard 2.0:
https://www.nuget.org/packages/System.Text.Json/4.6.0-preview6.19303.8

**Comment by jemiller0** [comment]
I was thinking it used Span<T> and made use of new things in the .NET Core runtime which they weren't going to add to .NET Framework. Maybe I'm confusing that with the latest C# language features that they added which will not be supported on .NET Framework.

**Comment by jemiller0** [comment]
I was wrong about that. It says here https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/ that it works with .NET Framework.

**Comment by hez2010** [comment]
.NET Standard 1.0 has been end of support therefore I think there's no need to support .NET Standard 1.x.

**Comment by jemiller0** [comment]
That may be, but, don't expect people to move off .NET Standard 2.0 anytime soon.

**Comment by hez2010** [comment]
You can multi-target your library to resolve it:
in .csproj file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.4;netstandard2.0;netstandard2.1</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Condition="'$(TargetFramework)' == 'netstandard2.1'" Include="System.Text.Json" Version="4.6.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
  </ItemGroup>
</Project>
```
in .cs file
```cs
#if NETCOREAPP3_0 || NETSTANDARD2_1
....
#else
...
#endif
```

**Comment by RicoSuter** [comment]
Thx, but referencing the library is the small problem, the blocker is this:
https://github.com/RicoSuter/NJsonSchema/issues/1014#issuecomment-504420986

**Comment by gdoddsy** [comment]
@RicoSuter - are you able to provide any more info on the solution for now? How do I add NSwag with a Newtonsoft.Json contract resolver?

**Comment by RicoSuter** [comment]
If you call AddOpenApiDocument() without using Newtonsoft in ASP.NET Core itself, it should still work but with a the default contract resolver. If the default contract resolver does not reflect what the actual serializer is doing, then you need to change the contract resolver so that it reflects the serializers (in the AddOpenApiDocument(options => options.SerializerSettings = ...)

**Comment by hez2010** [comment]
I think at least NJsonSchema should recognize JsonIgoreAttribute and other attributes in System.Text.Json while generating OpenApi schema.

**Comment by RicoSuter** [comment]
JsonIgoreAttribute from System.Text.Json?

**Comment by hez2010** [comment]
> JsonIgoreAttribute from System.Text.Json?

Sorry, that is a typo. It should be JsonIgnoreAttribute.

https://github.com/dotnet/runtime/blob/b0351370ccd132d95c97b75312fc36adaacc2664/src/libraries/System.Text.Json/ref/System.Text.Json.cs#L767

**Comment by jeremyVignelles** [comment]
`JsonIgnoreAttribute` isn't the only one that needs to be supported, here are other examples:
- [JsonExtensionDataAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonextensiondataattribute?view=netcore-3.1) : Same as JSON.Net, but only takes a `Dictionary<string,object>` or a `Dictionary<string, JsonElement>`. In the latter case, `JsonElement` should not be included in the generated schema.
- [JsonPropertyNameAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonpropertynameattribute?view=netcore-3.1) can be used to give the property a new name, the same way as JSON.NET's `[JsonProperty]`

and I probably missed other attributes...

**Comment by RicoSuter** [comment]
Ref: https://github.com/RicoSuter/NSwag/pull/2655

**Comment by RicoSuter** [comment]
We'd need to implement a custom Newtonsoft contract resolver which reads the System.Text.Json options and attributes and correctly maps them... see

https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/SystemTextJsonUtilities.cs#L33

**Comment by RicoSuter** [comment]
Ref: https://github.com/RicoSuter/NJsonSchema/pull/1173/commits/5981ecb1cb4810a111e4c17940e821601e486a3a

**Comment by RicoSuter** [comment]
@steveharter is there already a roadmap for serializer metadata discover (contract resolver)? Otherwise we need to use reflection and reimplement all your rules manually in the schema generator... (I really want to avoid that).

**Comment by panesofglass** [comment]
@RicoSuter Are there any additional steps where you could use some help? I would like to update my [F# wrapper](https://github.com/panesofglass/FSharp.Data.JsonSchema) with support for F# types to use the System.Text.Json support and would be happy to try to help get this over the finish line.

**Comment by RicoSuter** [comment]
@panesofglass thanks for your post.

Currently we map the System.Text.Json “rules” manually to the newtonsoft metadata with a custom contract resolver. 

https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/SystemTextJsonUtilities.cs#L45

This is a quick solution for now until STJ offers metadata directly. There are probably lots of edge cases and attributes missing... would be great if someone could help complete this (also more unit tests needed). Apart from that you can just set the SerializerOptions property on the generator settings and it will use these rules. 

https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/JsonSchemaGeneratorSettings.cs#L114

What is missing for you?

**Comment by panesofglass** [comment]
I don’t know whether anything is missing. I was uncertain whether this had been released, but it seems it has? I’m happy to look into adding some tests.

**Comment by panesofglass** [comment]
I have not yet added tests to this repo, but I've been able to switch to `System.Text.Json` in the other project. I'll still try to get back to adding tests here.

**Comment by RicoSuter** [comment]
Ref 
https://github.com/RicoSuter/NJsonSchema/pull/1333
https://github.com/RicoSuter/NJsonSchema/pull/1331

**Comment by razerez** [comment]
Can this be used in the nswag cli as well? can't see it in the man page:
` dotnet nswag aspnetcore2openapi /project:MyServerExample.csproj /documentName:v1 /output:swagger.json`
