### ISSUE TITLE
Documentation not updated

### ISSUE THREAD

**Issue by HSyr** [RicoSuter/NJsonSchema#1016]
Documentation for both `CSharpGeneratorSettings.ArrayBaseType` and `CSharpGeneratorSettings.ArrayType` says "default (value is): 'ObservableCollection'" which was true with the previous version.  Default value is `System.Collections.ObjectModel.Collection` and `System.Collections.Generic.ICollection` respectivelly.

**Comment by RicoSuter** [comment]
Thanks for reporting, could you update the wiki?

**Comment by HSyr** [comment]
The wrong documentation text is in the source code https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.CSharp/CSharpGeneratorSettings.cs. I am not aware of the wiki text.
