### ISSUE TITLE
Discriminator value for Typescript class from Json schema mappings

### ISSUE THREAD

**Issue by LukZap** [RicoSuter/NJsonSchema#1021]
I'm using TypeScriptGenerator to generate couple of TS classes from my C# types. There are some inheritance stuff involved, so to generate proper Json schema I'm using custom JsonInheritanceConverter to nicely override default value for discriminator for derived classes by pattern "fullname, namespace" (for ex. "TestTypescriptGenerator.Models.TestDependency, TestTypescriptGenerator.Models" - Json serializer we use in our system needs that format). 

That in Json schema produces "mapping" property like:
         
```
"mapping": {
          "TestTypescriptGenerator.Models.TestDependency, TestTypescriptGenerator.Models": "#/definitions/TestDependency"
}
```

and then in TS class in fromJS() method - results in checks like:
```
if (data["$type"] === "TestTypescriptGenerator.Models.TestDependency, TestTypescriptGenerator.Models") {
            let result = new TestDependency();
            result.init(data);
            return result;
}
```
so when passing Json like below - everything is working correctly:
```
{
      "$type":"TestTypescriptGenerator.Models.TestDependency, TestTypescriptGenerator.Models",
      "Amount":2.0
}
```

But going other way, when I want to get same Json by using autogenerated toJSON() method there are no mapping applied to discriminator field - it's just current class name.
```
constructor(data?: ITestDependency)
{
    super(data);
    this._discriminator = "TestDependency";
}
```

signature of toJSON() method in base class (just to recall)
```
toJSON(data?: any)
{
    data = typeof data === 'object' ? data : { };
    data["$type"] = this._discriminator;
    return data;
}
```
Json I get back is different from which I'm passing to fromJS() method:
```
{
      "$type":"TestDependency",
      "Amount":2.0
}
```

Is there a chance to change that behaviour to generate mapped discriminators for TS classes?

**Comment by RicoSuter** [comment]
This is a bug, _discriminator needs to resolve via mapping and not use schema key/type name directly

**Comment by RicoSuter** [comment]
Created PR: https://github.com/RicoSuter/NJsonSchema/pull/1043

**Comment by LukZap** [comment]
Thanks a lot!
