### ISSUE TITLE
NJson Validate does'nt work with Schema?

### ISSUE THREAD

**Issue by Verbeke** [RicoSuter/NJsonSchema#1023]
Hello, 

I'm using NJsonsoft to validate json with schema. I don't know if its normal or not because when i tried to validate my json on some json validator in internet, i had no errors. I tried to provok one error with string data for a boolean type.

My schema : 

{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "LivraisonRapportage",
  "description": "LivraisonRapportage",
  "type": "object",
  "properties": {
    "livrablesRapportage": {
      "description": "Que pour statut = TERMINE",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "diffusableClient": {
            "type": "boolean"
          }
        },
        "required": [
          "diffusableClient"
        ]
      },
      "minItems": 1
    }
  }
}

my json ; 

{
  "data": {
    "LivraisonRapportage": {
      "livrableRapportage": [
        {
          "diffusableClient": "azezaezae"
        }
      ]
    }
  },
  "context": {
    "flowName": "BOR_001_001",
    "applicationSource": "BOR"
  }
}

**Comment by RicoSuter** [comment]
Can you described the input/output, the current result and the expected result?

**Comment by Verbeke** [comment]
Sorry we found the answer. Json validation is permissive. When you add one node to root or after who are not in the schema, all nodes below this node won't take validation by schema. For this reason the validation didnt work with this example.
So we deleted nodes data and LivraisonRapportage to obtain the good error diffusableclient must be a boolean.
