### ISSUE TITLE
Can't load Namotion.Reflection when trying to read a schema from a file in a T4 template

### ISSUE THREAD

**Issue by ghostelet** [RicoSuter/NJsonSchema#1025]
I'm trying to generate some C# classes based on some JSON schemas using T4 templates. I have a very basic JSON schema:

`{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://dummyurl/countries.json",
  "title": "Countries",
  "description": "Description of countries",
  "properties": {
    "name": {
      "description": "Defines a country",
      "type": "string"
	}
  }
 }`

And the code of my T4 template looks like this:

`<#@ template hostspecific="true" language="C#" #>
<#@ assembly name="System.Core" #>
<#@ assembly name="$(NuGetPackageRoot)\namotion.reflection\1.0.5\lib\net45\Namotion.Reflection.dll" #>
<#@ assembly name="$(NuGetPackageRoot)\dotliquid\2.0.254\lib\net45\DotLiquid.dll" #>
<#@ assembly name="$(NuGetPackageRoot)\njsonschema\10.0.21\lib\net45\NJsonSchema.dll" #>
<#@ assembly name="$(NuGetPackageRoot)\njsonschema.codegeneration\10.0.21\lib\net451\NJsonSchema.CodeGeneration.dll" #>
<#@ assembly name="$(NuGetPackageRoot)\njsonschema.codegeneration.csharp\10.0.21\lib\net451\NJsonSchema.CodeGeneration.CSharp.dll" #>
<#@ import namespace="System.Threading.Tasks" #>
<#@ import namespace="NJsonSchema" #>
<#@ import namespace="NJsonSchema.CodeGeneration.CSharp" #>

<#
    var schema = Task.Run(() => JsonSchema.FromFileAsync(@"C:\tmp\NJsonSchema\countries.json")).GetAwaiter().GetResult();
    var generator = new CSharpGenerator(schema);
    var file = generator.GenerateFile();

	#><#= file #>`

When I run this template from Visual Studio I get an exception saying Namotion.Reflection cannot be found. If I debug the template then I get the expected output. If I put all files in the same folder (which I'd like to avoid anyway) it doesn't work either. I found this other issue also that looks very similar but it doesn't have a solution either: https://github.com/RicoSuter/NSwag/issues/358

The exception exactly says:

Running transformation: System.TypeInitializationException: The type initializer for 'NJsonSchema.JsonSchema' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Namotion.Reflection, Version=1.0.5.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102' or one of its dependencies. The system cannot find the file specified.
   at NJsonSchema.JsonSchema..cctor()
   --- End of inner exception stack trace ---
   at NJsonSchema.JsonSchema.<FromJsonAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.JsonSchema.<FromFileAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.JsonSchema.<FromFileAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TextTemplating31C71FCB030A0DE0B135EEF3DE7967FFC4564A1702C2516542BA0384669D289125B26D95F22CD8B2E1F11370B7A759B3647A50C6AD604118544BD74B30803E5E.GeneratedTextTransformation.TransformText()	[path to my T4 template]

**Comment by RicoSuter** [comment]
I think you also need to load the Namotion.Reflection assembly with a T4 tag.

**Comment by ghostelet** [comment]
Yes. Somehow it worked only after I restarted my PC though. Probably some caching issue somewhere... Thank you

**Comment by Shirabet** [comment]
Hi, I also ran into this problem with my project and I can’t figure out what to do. I tried restarting the computer and it didn’t help. The reference for namotion reflection version 2.0.1 comes from the njsonschema assembly and everything else uses version 2.0.3. Can I please get some help?
