### ISSUE TITLE
Generated code always uses type object for $ref

### ISSUE THREAD

**Issue by GLI14** [RicoSuter/NJsonSchema#1027]
Hi all, 

I would like to be able to generate code that returns the concrete type instead of "object". In my example I would expect that the type for 'testProp' would be MyClass instead of object. Could you please tell me what I am doing wrong and if this is possible.

Thx!

Schema :

``
{
                   '$schema': 'http://json-schema.org/draft-04/schema#',
                   'title': 'MyTest',
                   'type': 'object',
                   'additionalProperties': false,
                
                   'definitions': {                      
                      'MyClass': {
                         'additionalProperties': false,
                         'type': 'object',
                         'properties': {
                            'value': { 'type': 'string' }
                         }
                      }
                   },

                   'properties': {                       
                        'testProp': { 'type':  { '$ref': '#/definitions/MyClass' } }                 
                   }
                }`
```




Generated file : 
//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.0.21.0 (Newtonsoft.Json v12.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace MyNamespace
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.21.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class MyClass 
    {
        [Newtonsoft.Json.JsonProperty("value", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Value { get; set; }
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.21.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class MyTest 
    {
        [Newtonsoft.Json.JsonProperty("testProp", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public object TestProp { get; set; }
    
    
    }
}

**Comment by RicoSuter** [comment]
"type" is an enum ("string", "number", "object") and cannot be a $ref to another schema.

Try `'testProp': { '$ref': '#/definitions/MyClass' }`
