### ISSUE TITLE
Manual schema generation with Array

### ISSUE THREAD

**Issue by thrixton** [RicoSuter/NJsonSchema#1029]
I'm trying to manually create a schema for an array of dynamic objects.
I can construct the dynamic object schema, but cannot work out how to get the "outer" array 
schema which references the object schema.

I've tried adding it to an outer array schema via the `Definitions.Add` method but to no avail.

Is there any documentation on how to do this?
I'd be happy to write up a PR if someone can help me and it'd be useful.

Thanks.

**Object Schema**

```csharp
foreach (DataRow row in schema.Rows)
{
  var name = (string)row["ColumnName"];
  var type = (Type)row["DataType"];
  jSchema.Properties.Add(name, new JsonSchemaProperty() { Title = name, Type = JsonObjectType.Boolean });
}
```

**Desired Schema**
```json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "type": "array",
    "items": {
        "$ref": "#/definitions/DataRowElement"
    },
    "definitions": {
        "DataRowElement": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "boolean"
                }
            },
            "required": [
                "id"
            ],
            "title": "DataRowElement"
        }
    }
}
```

**Comment by RicoSuter** [comment]
I think it's `jSchema.Properties["propertyName"] = new JsonSchemaProperty { .... }`

**Comment by thrixton** [comment]
Hi @RicoSuter, Thanks for replying.
I can generate the properties OK, what I cannot figure out how to do is to reference the schema object as the outer array elements.

I've created a quick program illustrating the problem.
https://github.com/thrixton/JsonSchemaGenTest
I really appreciate your work and help.
Thanks

**Comment by thrixton** [comment]
Never mind, I ran this through the `FromSampleJson` and figured out I needed to set the `Item` property to a new `JsonSchema` with a reference to the inner schema.
Thanks for your help and work.
