### ISSUE TITLE
Using JsonSchema.FromType without a type

### ISSUE THREAD

**Issue by darkl** [RicoSuter/NJsonSchema#1038]
Hi, cool project!

I am interested in the following scenario: I want to create a JsonSchema representing the parameters of a given `MethodInfo`. The behavior I'm looking for is the same as if the method was a class having all these parameters as properties with the corresponding names and types. I was wondering if there is a simple way to achieve this, for instance, can I somehow create an instance of a `ContextualType` and define programatically its properties to be my desired properties? Or should I copy/paste the code from the `JsonSchemaGenerator` class and modify it for my scenario?

Thanks!
Elad

**Comment by RicoSuter** [comment]
You'd create a document, a resolver and a generator and then loop through the params, something like this

            var schema = new JsonSchema();
            var resolver = new JsonSchemaResolver(schema, _settings);
            var generator = new JsonSchemaGenerator(_settings);

            foreach (var parameter in parameters)
            {
                   schema.Properties[parameter.Name] = await generate.Generate...(... parameter.ToContextualType())
            }

**Comment by darkl** [comment]
>
> Ok, I'll give it a try.

Thanks!
Elad

>

**Comment by darkl** [comment]
How can I create a `JsonSchemaProperty` from the above generated `JsonSchema`?

**Comment by darkl** [comment]
I think I figured it out:

```csharp
JsonSchema schema = new JsonSchema();
JsonSchemaResolver resolver = new JsonSchemaResolver(schema, _settings);
JsonSchemaGenerator generator = new JsonSchemaGenerator(_settings);

foreach (ParameterInfo parameter in methodInfo.GetParameters())
{
    schema.Properties[parameter.Name] = 
        generator.GenerateWithReferenceAndNullability<JsonSchemaProperty>(parameter.ToContextualParameter(), resolver);
}
```
