### ISSUE TITLE
Flags enums generated from Swagger.json have incorrect values

### ISSUE THREAD

**Issue by Jehoel** [RicoSuter/NJsonSchema#1042]
My web-service exposes a `[Flags]` enum originally defined in C# as:

```
[Flags]
public enum AnnouncementDismissalTypes : Byte
{
	/// <summary>The announcement cannot be dismissed.</summary>
	None = 0,

	/// <summary>The announcement will only be shown to a user once and never again. Users may opt-in to receive the announcement again if <see cref="AllowReminder"/> is set.</summary>
	AllowAutomaticDismissal = 1,

	/// <summary>The user can permamently dismiss the announcement. The dismissal must be saved in the web-service.</summary>
	AllowManualDismissal = 2,

	/// <summary>The user can dismiss the announcement for 12 hours or until their next new session. The dismissal may be saved in the web-service but this is not necessary, e.g. if using the user's cookies.</summary>
	AllowReminder = 4,

	_All = AllowAutomaticDismissal | AllowManualDismissal | AllowReminder
}
```

The `Swagger.json` file generated by NSwag in the ASP.NET Core project describes the enum correctly:

```
"AnnouncementDismissalTypes": {
      "type": "integer",
      "description": "",
      "x-enumFlags": true,
      "x-enumNames": [
        "None",
        "AllowAutomaticDismissal",
        "AllowManualDismissal",
        "AllowReminder",
        "_All"
      ],
      "enum": [
        0,
        1,
        2,
        4,
        7
      ]
    },
```

However the NSwag Studio C# client code generator generated this incorrect `enum` definition:

```
[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.22.0 (Newtonsoft.Json v11.0.0.0)")]
[System.Flags]
public enum AnnouncementDismissalTypes
{
    None = 1,
    AllowAutomaticDismissal = 2,
    AllowManualDismissal = 4,
    AllowReminder = 8,
    _All = 16,
}
```

Observe how it has recomputed the values for the flags members and disregarded the original enum values from the Swagger file.

Also, I have XML-documentation Swagger help generation enabled, but it doesn't seem to be using the XML documentation for the original `enum` in Swagger. In fact the Swagger UI page doesn't describe the `enum` at all (it lists it only as `AnnouncementDismissalTypes: integer` with `[ 0, 1 ]` above it for some reason:

![image](https://user-images.githubusercontent.com/1693078/63243629-fc051400-c20f-11e9-9b9a-193fb3ed2b41.png)

**Comment by RicoSuter** [comment]
The problem is this here: 
https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.CSharp/Models/EnumTemplateModel.cs#L72

I think we need to check whether `value` is an integer and just use this otherwise keep the current logic.

**Comment by Jehoel** [comment]
I've got a fix, making a PR now.

**Comment by phirivie** [comment]
Hi,

I'm using NSwag.MSBuild version 13.17.0 with NJsonSchema version 10.8.0.0 and I have the same problem as above

Example:

TestEnumDto:
      type: integer
      enum: [1, 2, 4, 5]
      x-enumFlags: true
      x-enumNames:      
      - One
      - Two
      - Four
      - CombineOneAndFour

Once generated, CombineOneAndFour becomes 8 and should be 5 to follow enum array

Kr,
Philippe
