### ISSUE TITLE
Can't find the property OperationProcessors

### ISSUE THREAD

**Issue by samneefs** [RicoSuter/NJsonSchema#1051]
I want to add an OperationProcessor (for a header parameter), but don't find to option described in
https://github.com/RicoSuter/NSwag/wiki/Document-Processors-and-Operation-Processors

Here it says:
> Custom processors can be added with the settings object, e.g.
> settings.OperationProcessors.Add(new MyOperationProcessor());

However it doesn't say where I can find the settings object and what type it is.
I expected it to be "SwaggerUi3Settings", which is found trough the startup:
   ```
     public static void RegisterWebApi(this IAppBuilder app, HttpConfiguration config)
        {
            app.UseSwaggerUi3(typeof(Startup).Assembly, settings =>
            {
                settings.
```

However this object doesn't have the expected property.

Where can I set this property?

**Comment by RicoSuter** [comment]
It's on the settings.GeneratorSettings property

**Comment by samneefs** [comment]
Thanks, now I see it and it works
