### ISSUE TITLE
Number 'format' is ignored when the spec is defined via reference ($ref)

### ISSUE THREAD

**Issue by alexbutler-iress** [RicoSuter/NJsonSchema#1068]
When trying to generate code from a YAML we've received, we were getting Int32 out of range exceptions from the code generator.

It transpires that if the field is defined via reference, the format seems to be ignored. After de-referencing the fields, the issue went away.

However, we need a fix for this as we can't keep editing a contractual YAML to factor out the referencing for the affected fields each time we receive a new version

[NSwag Issue with Number Formats.txt](https://github.com/RicoSuter/NJsonSchema/files/3670945/NSwag.Issue.with.Number.Formats.txt)

**Comment by RicoSuter** [comment]
Please provide a sample

**Comment by alexbutler-iress** [comment]
As requested, hopefully this shows the problem with ease.

[NSwag Issues.zip](https://github.com/RicoSuter/NJsonSchema/files/3733494/NSwag.Issues.zip)

**Comment by alexbutler-iress** [comment]
Hi @RicoSuter, have you had any joy with this issue. It's a bit of a thorn on our side at the moment.

**Comment by RicoSuter** [comment]
Currently I don't have time to look into this. You'd need to reproduce this with a JSON Schema unit test and fix at the place where the format is read and instead of schema.format use schema.ActualSchema.Format (i think)
