### ISSUE TITLE
C# generator: Generate C# 8 Nullable Reference Type (NRT) attributes

### ISSUE THREAD

**Issue by RicoSuter** [RicoSuter/NJsonSchema#1069]
Add new setting for this feature.

**Comment by adamjones1** [comment]
It would be great to have this. If I understand right, this issue is only for client generation, so shouldn't the implementation of this not need to meddle with the NRT attributes at all and simply need to know when to syntactically add a `?` to a type name like it already does with structs? This should be quite easy since the logic is presumably already in place for structs (but ignored for reference types), right?

**Comment by RicoSuter** [comment]
> If I understand right, this issue is only for client generation, so shouldn't the implementation of this not need to meddle with the NRT attributes at all and simply need to know when to syntactically add a ? to a type name like it already does with structs? 

Exactly, it’s probably not super trivial but it will be an opt-in setting so it will no break existing user and it doesnt matter if its not working 100% at the beginning.

**Comment by RicoSuter** [comment]
Good idea, however adding `#nullable disable` is probably a breaking change when not using C# 8, right?

**Comment by jeremyVignelles** [comment]
Didn't think about that. Probably worth having an option to disable it, you're right.

We then have four states:
- Disabled
- Explicitely disabled
- Enabled
- Explicitely enabled

Or maybe it's better to have an option like "C# output language level" and use `#nullable enable` only for C#8 and above?
That would pave the way for C#9 records/init only, right?

**Comment by RicoSuter** [comment]
> Or maybe it's better to have an option like "C# output language level" and use #nullable enable only for C#8 and above?

Good idea but not sure about that, I think NRT would be the only thing which would check that - and then it's probably better to a have a specific option... for everything else i think we can just generate eg C# 6 code and there is just no downside (unlike in TS).

> That would pave the way for C#9 records/init only, right?

I think it would be better to have another class style here: 

![image](https://user-images.githubusercontent.com/2603405/84365350-9c7a5980-abd1-11ea-98a0-0f160de02bf5.png)

**Comment by jeremyVignelles** [comment]
I was thinking about it more as a safeguard to avoid using settings unavailable for the target language level, but OK for your NativeRecord suggestion.

About the `#nullable disable`, what would you suggest ? A drop down with the 4 options I described above? (Or 3 if we decide that implicitely `Enabled` option is useless)

**Comment by RicoSuter** [comment]
What about a boolean setting "GenerateNullableReferenceTypes" (default: false) and for now it just generates `#nullable disable` and then we can just implement it? How bad is that?

**Comment by jeremyVignelles** [comment]
Probably a bit misleading if NRT are not really implemented.

How hard would it be to implement NRT directly behind the flag ?

**Comment by RicoSuter** [comment]
> How hard would it be to implement NRT directly behind the flag ?

I think it should be quite simple to implement - we already have it for typescript.. at least for the public api contract - not sure whether we have problems “inside” the methods etc but there we could just disable the checks at the beginning

**Comment by RicoSuter** [comment]
I think we only need to add a ? if the reference type is nullable and the setting is enabled here: 
https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.CSharp/CSharpTypeResolver.cs#L137

I think the others in this method use Nullable<> and are already handled correctly - or what do you think?

**Comment by RicoSuter** [comment]
Not sure but this might already be enough: 
https://github.com/RicoSuter/NJsonSchema/pull/1193

**Comment by jeremyVignelles** [comment]
I don't see any other case where this might break something:
- nullable parameters are probably already checked for nullability
- nullable return is likely already handled as well
- nullable properties : You don't handle them directly in the generated code, right? so no problem here.

Problems will arise when used in a project if the code using that doesn't match the intent, but that's the whole point of enabling that, and it's opt-in.

I don't see anything else problematic

**Comment by RicoSuter** [comment]
My thinking was that if you have warnaserror enabled and the flow analysis within the method gives warnings it would turn them into errors and thus wont compile - but i think we disable all warnings in the generated code so this might also be fine...

**Comment by jeremyVignelles** [comment]
I don't understand : If that's an opt-in feature, it would only break if you tell it to enable NRT, right ?
What kind of flow analysis would break anything?

**Comment by RicoSuter** [comment]
My PR above probably is already enough because this resolver is used for method params, return param and POCO property types... the "problem" is - also with NRT in general - that it's only a compile time feature - so if the server returns wrong JSON (ie null but the property is not-nullable) then there will be no exception at runtime, this could be solved with this: 

https://github.com/RicoSuter/Namotion.Reflection#validate-nullability-c-8

but this is a topic we won't cover in this issue probably.

**Comment by RicoSuter** [comment]
> What kind of flow analysis would break anything?

For example if NRT is enabled and your param is non nullable but in the generated method we still check it against null this might give a warning (eg check not needed) which might be a problem... but it's something we need to try out and improve over time I think...

**Comment by jeremyVignelles** [comment]
Isn't there any check in the Json serializer that checks the [Required] and [JsonProperty] attributes and checks whether the deserialized json is valid w.r.t the specified attributes?

**Comment by RicoSuter** [comment]
Can you check my PR above (i.e. go through the changed class). 

Does it look good? 
Would you be willing to add some unit tests for that later?

**Comment by RicoSuter** [comment]
> Isn't there any check in the Json serializer that checks the [Required] and [JsonProperty] attributes and checks whether the deserialized json is valid w.r.t the specified attributes?

Ah you are right!
I was thinking about own written code where you dont have JsonProperty attributes but only the NRT info - there you'd have this problem... in our generated code the NRT and JsonProperty attribute would be in sync and the serializer even checks - so probably all good.

**Comment by RicoSuter** [comment]
Should we go with this PR? As its a new, experimental setting (opt-in) I can merge and release that now and you can try it out and then we add tests + improve on that... what do you think?

**Comment by jeremyVignelles** [comment]
I've read your PR and didn't find anything wrong, but I don't have your knowledge of this project, and I don't know what impact it has.

> Should we go with this PR? As its a new, experimental setting (opt-in) I can merge and release that now and you can try it out and then we add tests + improve on that... what do you think?

OK, but I won't be able to test before Monday.

**Comment by jeremyVignelles** [comment]
Also, for my use case (NSwag code gen), would I need a new release of NSwag too ?

**Comment by jeremyVignelles** [comment]
I can't find a better name, and "Nullable Reference Types" is the way that feature is named in the C# language. I'm ok with that naming.

**Comment by RicoSuter** [comment]
![image](https://user-images.githubusercontent.com/2603405/84443494-ff0a3e80-ac3f-11ea-8e0d-ea88b6b0c1dd.png)

**Comment by RicoSuter** [comment]
Ref: https://github.com/RicoSuter/NJsonSchema/issues/1195

**Comment by jeremyVignelles** [comment]
Oops, I completely missed that the PR you were sending didn't include #nullable annotations, sorry

**Comment by jeremyVignelles** [comment]
Since this has been released, can it be closed now ?

**Comment by adamjones1** [comment]
I get a whole bunch of compiler warnings from the generated `ConvertToString` method enabling this (happy to raise this as a separate issue if you prefer).

Almost all of them can be resolved as marking the method with `[return: NotNullIfNotNull("value")]`, and adding a little sanity check within the method to default to the empty string for the rare case when `value` is non-null but the method otherwise returns null because `value.ToString()` is null.

The rest of them are when there's a query parameter list of nullables, eg. `IEnumerable<string?>`. It tries to URI-escape each of the strings but fails when one is null. Probably sensible to default to `QueryNullValue` from the NSwag config file in this case.

**Comment by jeremyVignelles** [comment]
@adamjones1 : The ConvertToString issues are covered by #2959

**Comment by adamjones1** [comment]
Great, thanks. For the list ones, I get code generated like this for a method:

```
public async System.Threading.Tasks.Task<System.Collections.Generic.ICollection<MyResultDto>> GetResultsAsync(System.Collections.Generic.IEnumerable<string?>? ids = null)
{
    var urlBuilder_ = new System.Text.StringBuilder();
    urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/getResults?");
    if (ids != null) 
    {
        foreach (var item_ in ids) { urlBuilder_.Append(System.Uri.EscapeDataString("ids") + "=").Append(System.Uri.EscapeDataString(ConvertToString(item_, System.Globalization.CultureInfo.InvariantCulture))).Append("&"); }     
    }

    ...
}
```

Here what's going in to `ConvertToString` is nullable so the output is legitimately nullable and there's still a warning at `EscapeDataString`. Would be great if you could add a null-coalesce to that in your PR!

**Comment by jeremyVignelles** [comment]
Implemented in the PR. Do you have the ability to try in my PR and tell me if it work ?
There's the NSwag.ConsoleCore that you can run with the nswag.json file you want.

**Comment by adamjones1** [comment]
Just tried it, I get compiler errors because `item_` and `""` are of different types in some cases (in my example it was an `IEnumerable<string?>` but it could in general be an enumerable of anything). An upcast to `object?` should fix it.

**Comment by jeremyVignelles** [comment]
You're right, might have missed that. Let me fix that

**Comment by jeremyVignelles** [comment]
Does it work better now ?

**Comment by adamjones1** [comment]
Looks good, no compiler or runtime errors/warnings for me 👍

**Comment by RicoSuter** [comment]
Closed as implemented and released, please create new issues if there are bugs/problems with the current implementation.
