### ISSUE TITLE
Unable to globally configure type discriminators

### ISSUE THREAD

**Issue by Porl91** [RicoSuter/NJsonSchema#1088]
I have the following types:

```cs
public abstract class BaseType
{
	public int BaseProp { get; set; }
}

public sealed class DerivedType : BaseType
{
	public int DerivedProp { get; set; }
}
```

Without using the `JsonInheritanceConverter` attribute to add a discriminator to `BaseType` as suggested on this page:
https://github.com/RicoSuter/NJsonSchema/wiki/Inheritance

Is it possible to globally configure `BaseType` with this configuration? The reason I ask is because I'm unable to add this attribute to the type itself as it lives in a context that I can't add refer to NJsonSchema attributes.

I was hoping this could be achieved using the `DiscriminatorSchemaProcessor` processor, but adding this as a processor doesn't seem to have changed the JSON schema that's been generated.

https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/SchemaProcessors/DiscriminatorSchemaProcessor.cs

The code I'm using to generate this schema is:

```cs
var settings = new JsonSchemaGeneratorSettings
{
	AllowReferencesWithProperties = true,
	GenerateAbstractProperties = true
};

var schema = new JsonSchema();
var resolver = new JsonSchemaResolver(schema, settings);
var generator = new JsonSchemaGenerator(settings);

var types = new Type[]
{
	typeof(BaseType),
	typeof(DerivedType)
};

foreach (var type in types)
{
	var typeSchema = generator.Generate(type, resolver);
	resolver.AppendSchema(typeSchema, type.FullName);
}

var json = schema.ToJson();

Console.WriteLine(json);
```

This produces the following JSON schema for these types:

```js
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "BaseType": {
      "type": "object",
      "x-abstract": true,
      "additionalProperties": false,
      "properties": {
        "BaseProp": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "DerivedType": {
      "allOf": [
        {
          "$ref": "#/definitions/BaseType"
        },
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "DerivedProp": {
              "type": "integer",
              "format": "int32"
            }
          }
        }
      ]
    }
  }
}
```

If I add the following attribute to my definition of `BaseType`:
```cs
[Newtonsoft.Json.JsonConverter(typeof(NJsonSchema.Converters.JsonInheritanceConverter), "discriminator")]
```

I get the following JSON, which is what I'm after:

```js
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "BaseType": {
      "type": "object",
      "discriminator": {
        "propertyName": "discriminator",
        "mapping": {
          "DerivedType": "#/definitions/DerivedType"
        }
      },
      "x-abstract": true,
      "additionalProperties": false,
      "required": [
        "discriminator"
      ],
      "properties": {
        "BaseProp": {
          "type": "integer",
          "format": "int32"
        },
        "discriminator": {
          "type": "string"
        }
      }
    },
    "DerivedType": {
      "allOf": [
        {
          "$ref": "#/definitions/BaseType"
        },
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "DerivedProp": {
              "type": "integer",
              "format": "int32"
            }
          }
        }
      ]
    }
  }
}
```

The discriminator value is present and that will allow the CS / TS generators I'm using to create the correct mappings.
Adding the following under the definition of `generator` seems to only produce the first JSON snippet without the `discriminator` property:

```cs
generator.Settings.SchemaProcessors.Add(new DiscriminatorSchemaProcessor(typeof(BaseType), "discriminator"));
```

Any ideas where I'm going wrong here, or perhaps another way I can achieve the same effect without editing the original type definitions?

**Comment by RicoSuter** [comment]
Maybe it's best to clone this repo, create a unit test and debug the processor.

**Comment by Porl91** [comment]
I believe I've been able to fix this - as the `DiscriminatorSchemaProcessor` makes the assumption that the type has already set the `JsonInheritanceConverter` using the `JsonConverter`, as I'm not setting this it failed to process the type.

I've created a custom processor with the same implementation of `DiscriminatorSchemaProcessor` except it sets the `JsonInheritanceConverter` of the schema's `DiscriminatorObject` and just added that per abstract type in my types library and this seems to give me the result I want.
