### ISSUE TITLE
NSwag.CodeGeneration.TypeScript: const fields

### ISSUE THREAD

**Issue by gschmarri** [RicoSuter/NJsonSchema#1089]
We are using the NSwag TypeScript code generation to generate TypeScript files from .NET class definitions.
Just a question regarding const fields in generated TypeScript files.
Is there a way to generate TypeScript classes which contain some kind of const fields like this?

`
export class MyClass {
    myType: 'my-value';
}
`

We tried it in .NET with public const or static members, but did not manage to generate this kind of TypeScript const fields out of it.

Thanks for the help in advance.

**Comment by RicoSuter** [comment]
You cannot add this with the swagger spec only because you cannot describe it with the spec. But you could use extension code to add this manually, see 
https://github.com/RicoSuter/NJsonSchema/wiki/TypeScriptGenerator#extended-classes-and-extension-code

**Comment by gschmarri** [comment]
OK, thank you.
That's a helpful hint!
