### ISSUE TITLE
JsonContructor not read?

### ISSUE THREAD

**Issue by jwisener** [RicoSuter/NJsonSchema#1095]
This is a long shot, but I am wondering if there is a setting or someone has a recommendation for generating the swagger.json based on the C# constructors (I'm setting the JsonConstructor attribute), instead of the properties.  When we code our models, we keep them immutable which means that all properties (if exposed, would be getters only).  We also use the concept of "ValueObjects". So all that to say, the constructor (again, which I have marked as JsonConstructor) doesn't seem to get read by NSwag, am I doing something wrong? 

For example, our API may take a Phonumber as string: e.g.:

```
public class CustomerRequest
{
     [JsonConstructor]
     public CustomerRequest(string phoneNumber)
     { 
            PhoneNumber = new PhoneNumber(phoneNumber, addCountryCode=1);
     }

     public PhoneNumber PhoneNumber {get;}
}

public class PhoneNumber : ValueObject<PhoneNumber>
{
        private const string PHONE_REGEX = @"^(?!0+$)[0-9+-./()\s]+$";

        [JsonConstructor]
        public PhoneNumber(string phoneNumber)
        {
            Value = string.IsNullOrEmpty(phoneNumber) ? null : 
            AddPrefixIfNotPresent(Regex.Match(phoneNumber, PHONE_REGEX).Value.PhoneToNumbersOnly());
        }

        public string Value { get; }

        public string ValueWithoutCountryCode => Value?.Remove(0,1);

}
```

//Now, when I look at the definition in swagger ui: I see the following: 
//don't want this
{
  "customer": {
    **"phoneNumber": {
      "value": "string",
      "valueWithoutCountryCode": "string",
      "hasValue": true
     },**
  }
  ... //other props as well.
}

//the desired result, would be nice: 
{
  "customer": {
    **"phoneNumber": "string",**
  }
    ... //other props as well.
}

Note: I did add a typemapping and it did get the result; however, there we have alot of value objects. If we go with this approach every developer creating a new request for an api call, has to remember, go and add type mapping to nswag.   For phonumber it a "one string" for "one class", but we have some that may take say, 3 items in the constructor and that creates one value object. e.g. ( (string firstname, string middlename, string lastname) which gets turned into CustomerName(firstname, middlename, lastname).

Is there not a setting to inform nswag, (use the json constructor when generating the definition)? 

I guess, I could add a marker interface to every request object, and iterate over all of them and replace the existing schema objects, but I where would one do that? How do you "**find**" an item in the schema, "**remove it**", and "**create a new one**""?

Thanks,
Jason

**Comment by jwisener** [comment]
I guess no one is maintaining this project so closing.

**Comment by jwisener** [comment]
I guess no one is maintaining this project so closing.

**Comment by RicoSuter** [comment]
NJS uses newtonsoft’s contract resolver and i expect that ctor json attribute work because they are reported correctly. Needs investigation.

**Comment by jwisener** [comment]
Yeah, it works perfectly with .net core api's with hitting the api endpoints, but the generation of the swagger as well as the swagger ui, just ignores it.

**Comment by jwisener** [comment]
basically I kinda see it as there is no real solution to this. To override the generation of schema or to try and intercept the processing,  there are not really good of samples/examples/documentation on how to accomplish this. Maybe it's out there somehere, I just can't seem to find it. I wired up a schema processor but the object you have to deal is this "massive" god object with a very large number of properties on it.
