### ISSUE TITLE
Deserialize subclass from other library using JsonInheritanceConverter 

### ISSUE THREAD

**Issue by jeroendenhertog** [RicoSuter/NJsonSchema#1100]
We found a situation where we have a base class in C# library A and a subclass in C# library B. The classes are in different namespaces. 
When we do a http post of the subclass to an interface defined by the base class, the subclass is not deserialized. 
The normal solution would be to add the subclass to the knowntypes, but that would create a circular dependency.

I found that it's rather easy to find the right type to deserialize to using reflection:

`var type = AppDomain.CurrentDomain.GetAssemblies().
                SelectMany(a => a.GetTypes()).
                Where(t => t.IsSubclassOf(objectType)).
                Where(t => t.Name == discriminatorValue).
                FirstOrDefault();`

This may be something you'd like to cache and not repeat every time. There could be security issues with this approach, but those would be the same as you have when allowing $type as discriminator.

Would it be possible to add such functionality?

**Comment by RicoSuter** [comment]
I think you could override JsonInheritanceConverter and add this logic for correct serialization

**Comment by RicoSuter** [comment]
For correct schema generation you can provide a custom method to load known types

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.knowntypeattribute.methodname?view=netframework-4.8#System_Runtime_Serialization_KnownTypeAttribute_MethodName

https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/JsonSchemaGenerator.cs

(Method must be public i think)

**Comment by jeroendenhertog** [comment]
I didn't know you could define a method to define the knowntypes. Look like a very clean solution to this problem. Thanks!
