### ISSUE TITLE
Build Schema in Runtime

### ISSUE THREAD

**Issue by basil-twisleton** [RicoSuter/NJsonSchema#1114]
Hi Rico,

I am trying to build a schema in runtime based on some configuration in a database. 

Is this possible?

I cant find a way to create the properties and add them to the schema, as the Properties object is a readonly ICollection. 

Basic code would be something like
```
JsonSchema wholeSchema = new JsonSchema();

foreach (var field in fieldList)
{
    JsonSchema fieldSchema = new JsonSchema();
    fieldSchema.Name= field.Name;
    fieldSchema.Type = field.Type;
    wholeSchema.Properties.Add(fieldSchema);
}
```

Any pointers would be greatly appreciated, otherwise I will have to construct the JSON schema file manually and then parse it as a JsonSchema object. 

Thanks,
Basil

**Comment by RicoSuter** [comment]
Why doesnt your basic code work?

**Comment by basil-twisleton** [comment]
Trns out I was just off by a type of the properties. 

All workoing now. Thanks !

```
JsonSchema wholeSchema = new JsonSchema();

foreach (var field in fieldList)
{
    JsonSchemaProperty fieldSchema = new JsonSchemaProperty();
    fieldSchema.Type = field.Type;
    wholeSchema.Properties.Add(field.Name,fieldSchema);
}
```
