### ISSUE TITLE
Property Naming Policy - how to set

### ISSUE THREAD

**Issue by JonahKK** [RicoSuter/NJsonSchema#1129]
Hi,
I'm using `JsonSchema.FromType<>` to get the schemas. In order for it to work, my Dtos classes have to look like this:
```
public class ClassDto
    {
        [JsonProperty("data")]
        public Data Data { get; set; }
    }
```

I have been wondering is there any setting that would allow me to omit the _JsonProperty_? Currently omitting it will result in schema validation errors.

**Comment by RicoSuter** [comment]
Generator settings.SerializerSettings = new S { ContractResolver = new CamelCaseContractResolver()}

or similar (sorry i’m not on the pc right now)

**Comment by JonahKK** [comment]
Thanks, that was it!

For future reference (T is the generic):
```
var settings = new JsonSchemaGeneratorSettings
{
    SerializerSettings = new JsonSerializerSettings
    {
        ContractResolver = new CamelCasePropertyNamesContractResolver()
    }
};
var generator = new JsonSchemaGenerator(settings);
var schema = generator.Generate(typeof (T));
```

**Comment by RicoSuter** [comment]
So ContractResolver  is null when new JsonSchemaGeneratorSettings?

**Comment by JonahKK** [comment]
I've made a quick check and yes, it is null, when the new JsonSchemaGeneratorSettings is created.
![2020-02-18_08h20_20](https://user-images.githubusercontent.com/23238398/74712908-b9a4aa00-5227-11ea-8b4e-f549fad6cc2d.png)
