### ISSUE TITLE
How to serialize generated class?

### ISSUE THREAD

**Issue by grzesiekmq** [RicoSuter/NJsonSchema#1130]
How to serialize generated c# class from json schema?
I have in generated file the class Anonymous
but how to access the properties from this class from other file
so can then access properties of object
so I can do obj.Property;
![Screenshot from 2020-02-14 22-14-06](https://user-images.githubusercontent.com/9611210/74571353-fc435980-4f7d-11ea-8c5c-016582dcbf21.png)

**Comment by RicoSuter** [comment]
var x = new Anonymous()?

I dont understand your question.

**Comment by grzesiekmq** [comment]
nvm
