### ISSUE TITLE
Generate Inline Schema

### ISSUE THREAD

**Issue by lexusmarchuk** [RicoSuter/NJsonSchema#1160]
Hello,
Is it possible to configure Generator not to generate Definitions, but put all property's fields in the same tree?

For example Newtonsoft.JSchemaGenerator has option **SchemaLocationHandling.Inline**.
Using it - I can get schema like this:
```
{
  "type": "object",
  "properties": {
    "criteria": {
      "type": "object",
      "properties": {
        "basic": {
          "type": "object",
          "properties": {
            "account": {
              "type": "object",
.....
```

I can't find if there is a such option in NJsonSchema.

Thanks

**Comment by RicoSuter** [comment]
I think there is no out of the box option for that. You’d need to customize the generator..
