### ISSUE TITLE
ToSampleJson generates extra null entry at end of table

### ISSUE THREAD

**Issue by digitalsigi** [RicoSuter/NJsonSchema#1164]
First, thx for this great package. 
I use it to generate json schemas from C# classes derived from scaffolded SQL DB and want to generated sample data. 
Schema generation works like a charm, but ToSampleJson creates invalid sample data.
Sample Schema
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "AdressenArtJson",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "AdressenArt"
  ],
  "properties": {
    "AdressenArt": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/AdressenArt"
      }
    }
  },
  "definitions": {
    "AdressenArt": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "AenderungKng",
        "Beschreibung",
        "KurzBez",
        "Bearbeiter"
      ],
      "properties": {
        "AdressArtId": {
          "type": "integer",
          "format": "byte"
        },
        "AenderungKng": {
          "type": "string",
          "maxLength": 1,
          "minLength": 1
        },
        "Beschreibung": {
          "type": "string",
          "maxLength": 255,
          "minLength": 1
        },
        "KurzBez": {
          "type": "string",
          "maxLength": 50,
          "minLength": 1
        },
        "BearbDatum": {
          "type": "string",
          "format": "date-time"
        },
        "Bearbeiter": {
          "type": "string",
          "maxLength": 50,
          "minLength": 1
        }
      }
    }
  }
}
```
and the resulting sample data
```
{
  "AdressenArt": [
    {
      "AdressArtId": 0,
      "AenderungKng": "I",
      "Beschreibung": "Beschreibung",
      "KurzBez": "KurzBez",
      "BearbDatum": "2020-04-18T10:32:04.0646539+00:00",
      "Bearbeiter": "Bearbeiter"
    },
    null
  ]
}
```
The final null results - as expected - in a schema validation error
Josef

**Comment by RicoSuter** [comment]
Yes, this is problem with the current, "naive" and unfinished at the moment. 

https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/SampleJsonDataGenerator.cs

Probably we should just remove the second item of the array: 
https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/SampleJsonDataGenerator.cs#L53

But right now each schema is only generated once as object and then inserted as "null" which might lead to more problems. 

Can you help here and create a PR with improvements and unit tests?

**Comment by digitalsigi** [comment]
Thx for looking into it. I argued already, that this may be the problem. 
I've never done a PR before, but I could try. May take a few days...

**Comment by digitalsigi** [comment]
Well, I just discovered, there seem to be more problems. 
I have a field with maxlength=1 and ToSampleJson inserts the full name which is longer than 1 char.
So I think he PR has to wait, as I am in a rather large project and I would have to dig into much deeper than expected.

**Comment by RicoSuter** [comment]
I think the original issue is fixed by this PR: 
https://github.com/RicoSuter/NJsonSchema/pull/1169

Can you confirm?

**Comment by digitalsigi** [comment]
Yes, sure.
I looked at the code, sounds reasonable.
Have some schedules to meet, would have to wait.
