### ISSUE TITLE
Make DefaultReflectionService.IsStringEnum virtual

### ISSUE THREAD

**Issue by InspiringCode** [RicoSuter/NJsonSchema#1187]
Hi Rico,

could you please make DefaultReflectionService.IsStringEnum also virtual? I add a custom StringEnumConverter to JsonSerializationSettings.Converters that excludes certain enum types so they (the excluded enum types) have to be handled as numeric enums by NJsonSchema/NSwag.

I hope there are now objections to this suggestion.

Thank you,
Daniel

**Comment by RicoSuter** [comment]
https://github.com/RicoSuter/NJsonSchema/commit/1e343ee5c063ae059527bef95397dc6ce74aa16c
