### ISSUE TITLE
Null Reference Types cause CS8669

### ISSUE THREAD

**Issue by AceHack** [RicoSuter/NJsonSchema#1195]
```
warning CS8669: The annotation for nullable reference types
    should only be used in code within a '#nullable' annotations context. Auto-generated code
    requires an explicit '#nullable' directive in source.
```
Please add explicit #nullable when null reference types are used.  This happens even with Nullable is turned on at the project level.

**Comment by RicoSuter** [comment]
> This happens even with Nullable is turned on at the project level.

My idea was that you’d turn this on in the csproj - but this doesnt work because its autogenerated?

**Comment by jeremyVignelles** [comment]
@AceHack : FYI, I opened #1201 to fix your issue. I've also added `=default!;` to all properties if no default value is provided and GenerateNRT is enabled. Would you like to try the branch and see if it works for you ?
