### ISSUE TITLE
JsonFormatStrings.Guid and JsonFormatStrings.Uuid format resulted in 'guid'

### ISSUE THREAD

**Issue by satuday** [RicoSuter/NJsonSchema#1219]
When Format is set to JsonFormatStrings.Guid or JsonFormatStrings.Uuid, currently the resulting json spec show format:"guid".  is there any reason for this? shouldnt it be "uuid" as uuid is more universal and guid is more .net specific? advantage of using 'uuid' is it is also validated by swagger ui.

**Comment by RicoSuter** [comment]
If you use JsonFormatStrings.Uuid it should then output "uuid" is that not the case?

https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/JsonFormatStrings.cs#L33

**Comment by satuday** [comment]
yup.. you are correct. works when I set it to JsonFormatStrings.Uuid.  thanks.
