### ISSUE TITLE
How to create a general api information part?

### ISSUE THREAD

**Issue by GambaJo** [RicoSuter/NJsonSchema#1220]
NSwag works fine for me. But it only generates the UI from the contollers and the xml documentation. I want to show additional informations about my api because I want to minimize questions from developers that works with my api.

Example (I know it's not NSwag): https://amagno.me/api/v2/swagger/ui/index

You can see first a part with general, authentication and security hints. After this comes the api description. How can I make a similar genaral part?

**Comment by RicoSuter** [comment]
The sample just has HTML in the description - you can set this with PostProcess.

**Comment by GambaJo** [comment]
@RicoSuter Thx for the hint. I tried it and I can use html in this property.
