### ISSUE TITLE
Add suffix support for JsonInheritanceConverter

### ISSUE THREAD

**Issue by Pzixel** [RicoSuter/NJsonSchema#1235]
In most real cases discriminator are much terser than full class names. For example

```cs
[JsonConverter(typeof(JsonInheritanceConverter), "Type")]
abstract class MySomethingDiscriminator {}

class MyFooVeryLongDiscriminator : MySomethingDiscriminator {}
class MyBarVeryLongDiscriminator : MySomethingDiscriminator {}
```

Now you are forced to use `"type" : "MyFooVeryLongDiscriminator"` everywhere.

It would be much nicer to have an additional parameter named `suffix`:

```cs
[JsonConverter(typeof(JsonInheritanceConverter), "Type", "VeryLongDiscriminator")]
abstract class MySomethingVeryLongDiscriminator {}

class MyFooVeryLongDiscriminator : MySomethingDiscriminator {}
class MyBarVeryLongDiscriminator : MySomethingDiscriminator {}
```

so in JSON we could have just `"type": "MyFoo"` or `"type": "MyBar"`

**Comment by RicoSuter** [comment]
Can't you implement this in a custom converter which inherits from JsonInheritanceConverter? It is kept simple and without much options intentionally and you can extend it yourself if needed...

**Comment by Pzixel** [comment]
I think it's quite generic feature since people tend to name class in `JavaStyleWithBeanAwareFactoryLikeNames`  which in the same time doesn't fit typical JSON. So i thought that this 1:1 correspondence is quite awkward. Ideally we'd better have some alternative to `KnownType` to allow to specify any customization, but this is probably not feasible.

**Comment by RicoSuter** [comment]
As i said you can implement a MyJsonInheritanceConverter : JsonInheritanceConverter and remove the suffix in the serialized objects + the generated spec.

**Comment by danielwinkler** [comment]
For anybody interested this is how you could accomplish @Pzixel 's idea

```csharp
public class DTOConverter : JsonInheritanceConverter
{
    private readonly string _stripper;

    /// <summary>Initializes a new instance of the <see cref="JsonInheritanceConverter"/> class.</summary>
    /// <param name="discriminator">The discriminator.</param>
    /// <param name="stripper">Remove the string from the end of the type for the mapping.</param>
    public DTOConverter(string discriminator, string stripper) : base(discriminator)
    {
        _stripper = stripper;
    }
    protected override Type GetDiscriminatorType(JObject jObject, Type objectType, string discriminatorValue)
    {
        return base.GetDiscriminatorType(jObject, objectType, discriminatorValue + _stripper);
    }
    public override string GetDiscriminatorValue(Type type)
    {
        if (type.Name.EndsWith(_stripper))
        {
            return type.Name.Substring(0, type.Name.Length - _stripper.Length).ToLowerInvariant();
        }

        throw new InvalidOperationException("Type '" + type.Name + "' is not supported to be stripped with '" + _stripper + "'.");
    }
}
```

super nice work @RicoSuter !
