### ISSUE TITLE
Problem loading a file with # on its paths

### ISSUE THREAD

**Issue by shadow-cs** [RicoSuter/NJsonSchema#1257]
Whenever there is a `$ref` which resolves to a full path with a `#` character in it, the library will fail to load it (as it treats it as fragment instead of file path). The `$ref` itself doesn't need to (and shouldn't) have a `#` character in it (as part of the path, which would be incorrect URI as it should be escaped as `%23`), if the relative path in the `$ref` resolves to a path with `#` in it, the problem will surface.

### Solution

The source of the problem (sort-of see below) is how the `JsonReferenceResolver.ResolveFileReferenceWithAlreadyResolvedCheckAsync` splits the `fullJsonPath`:

```cs
var arr = Regex.Split(fullJsonPath, @"(?=#)");
```

Changing it to:

```cs
string[] arr;
var i = fullJsonPath.LastIndexOf('#');
if (i == -1)
{
    arr = new[] { fullJsonPath };
}
else
{
    arr = new[] { fullJsonPath.Substring(0, i), fullJsonPath.Substring(i) };
}
```

Resolves the issue in my case. But I'm not sure if it is universal enough to not cause any other issues (but according to JSON Pointer spec, `#` should only appear as the first character and having it somewhere else is an ill-formatted JSON Pointer).

Another solution would be to change how paths are resolved internally and use an `Uri` class (which would escape the `#`).

**Comment by RicoSuter** [comment]
Is this a problem with the new version 10.2 only?

**Comment by shadow-cs** [comment]
Not working in `10.1.26` either.

**Comment by RicoSuter** [comment]
Ok at least it didnt get worse, but im aware that external ref handling is not complete yet.

**Comment by RicoSuter** [comment]
See also: https://github.com/RicoSuter/NJsonSchema/pull/1098

I also want to fix that but we need to be very careful not to introduce regression.

**Comment by shadow-cs** [comment]
What is your preferred course of action? Should I submit a PR? Do you want some more time to evaluate?

My thoughts on this: According to [JSON Pointer spec](https://tools.ietf.org/html/rfc6901#section-6) `#` should only appear at the beginning of an URI fragment and the rest of the JSON Pointer should be URI escaped. So the real danger is in cases where someone would have a document with a `#` part of a type (definition/schema) name and uses a non-compliant JSON Pointer reference to it. I cannot imagine why someone would do this. I did however test this ([petstore.zip](https://github.com/RicoSuter/NJsonSchema/files/5299407/petstore.zip)) with both `swagger-cli` and `redoc-cli` and both do support the ill-formatted JSON pointer (and the well-formatted one as well). So if the changes I proposed above are accepted, there is some slight change of breaking something and to mitigate this more changes would be needed.

**Comment by RicoSuter** [comment]
Would this PR solve your problem? 
https://github.com/RicoSuter/NJsonSchema/pull/1098

Or do you need to apply your suggestions on top of it?
Can you head over to the PR and propose changes?
Ill look into this tomorrow.

**Comment by shadow-cs** [comment]
Fun fact: `Assembly.GetExecutingAssembly().CodeBase` returns something that looks like an URI but without `#` escaped (so it is not an URI after all, in Microsoft defense, they never stated it is an URI)

**Comment by shadow-cs** [comment]
> Would this PR solve your problem? #1098

No, I did look over it when you first mentioned it but I didn't see how it was relevant to my issue, I did test the branch to be extra sure but the code is outdated compared to `master` so it added more problems for me and did not solve anything.

> Or do you need to apply your suggestions on top of it?

I don't...

> Can you head over to the PR and propose changes?

I'd rather start a new PR (should be done in a few minutes). The changes are in different locations of `JsonReferenceResolver` so there shouldn't be conflicts. Please look over my changes and if you feel like it, we'll certainly find a way to integrate with #1098... Or we can just do one at a time.
