### ISSUE TITLE
why don't use StringComparison.OrdinalIgnoreCase on get property?

### ISSUE THREAD

**Issue by ehsanpishbaz** [RicoSuter/NJsonSchema#1267]
hi, on json data usually ignore case sensitive keies, i expect use **obj?.Property(propertyInfo.Key, StringComparison.OrdinalIgnoreCase)** on [this](https://github.com/RicoSuter/NJsonSchema/blob/693d851d79ec466fa354f8a39521d98d8df3bd6c/src/NJsonSchema/Validation/JsonSchemaValidator.cs#L357) line.

**Comment by RicoSuter** [comment]
I think properties in JSON Schema are not case insensitive, or are they? Can you post a link to the spec?

**Comment by ehsanpishbaz** [comment]
it's true, JSON aren't case insensitive, but not bad if validation method get a parameter for do this.

**Comment by lahma** [comment]
fixed by #1411
