### ISSUE TITLE
Releases not being updated with new version info

### ISSUE THREAD

**Issue by mdkiefer** [RicoSuter/NJsonSchema#1286]
I just upgraded from NSwag 12.0.11 to 13.9.4 and need to ensure some of my custom C# code generation templates are up to date. NSwag v12.0.11 (tag NSwag-Build-1045) uses NJsonSchema v9.13.13 (tag NSwag-Build-1872).  NSwag v13.9.4 (tag NSwag-Build-1118) uses NJsonSchema v10.3.1 per the published NuGet package. However, 10.3.1 doesn't show up in the 
 [NJsonSchema Releases](https://github.com/RicoSuter/NJsonSchema/releases). The latest version listed there is v10.0.4.

How do I figure out which commit corresponds to NJsonSchema v10.3.1?

**Comment by RicoSuter** [comment]
You can see it easily in the repo commit history

**Comment by mdkiefer** [comment]
Doh. Yep, it is there. I was used to looking under the Releases link to find the version. Thanks for the quick response.
