### ISSUE TITLE
I think `Validate` function is not working properly

### ISSUE THREAD

**Issue by yasharvc** [RicoSuter/NJsonSchema#1293]
Just try the following code:
`var res = (await JsonSchema.FromJsonAsync("{\"name\":\"abc\"}")).Validate("{\"name\":35}");`
this should return some error and `res.Count()` should be more than 0 but it returns 0.

**Comment by RicoSuter** [comment]
JsonSchema.FromJsonAsync requires a JSON Schema and not a JSON, you can use JsonSchema.FromSampleJsonAsync to generate a schema from a sample JSON - but this is not very reliable.
