### ISSUE TITLE
Merging several schema files into one

### ISSUE THREAD

**Issue by marian-margeta** [RicoSuter/NJsonSchema#1309]
Is it possible to merge schemas that was loaded using `JsonSchema.FromFileAsync()` method into one single json schema file?

**Comment by RicoSuter** [comment]
There is no out-of-the-box functionality where you can merge multiple JsonSchema objects into one, you'd need to do it manually.

**Comment by marian-margeta** [comment]
OK thank you. I found a workaround by putting both schema into the `allOf` property of one wapper schema.
