### ISSUE TITLE
Question: Reasons to choose format of "guid" over "uuid" for string?

### ISSUE THREAD

**Issue by martin-shields-sage** [RicoSuter/NJsonSchema#1322]
I have a question, I see that the JsonFormatStrings has an obsolete value for UUID and states to use GUID instead as uuid is redundant. However, if I have a JSON schema of..

```
"SubType" : {
              "type": "object",
              "properties": {
                "Id": {
                  "type": "string",
                  "format": "uuid"
                }
              },
              "required": [
                "Id"
              ]
            }
...
```

This does not get validated as a UUID or GUID type when running the validation against this schema without putting a new custom validator in to add UUID. Was there any reason why this was made redundant? When I look at the JSON schema specification I still see links to UUID being there - https://json-schema.org/draft/2020-12/json-schema-validation.html

**Comment by RicoSuter** [comment]
I think even if UUID is obsolete we should support it in the validator: 
https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/Validation/JsonSchemaValidator.cs#L28

**Comment by martin-shields-sage** [comment]
> I think even if UUID is obsolete we should support it in the validator:
> https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/Validation/JsonSchemaValidator.cs#L28

I would agree, it looks like the line which you have highlighted does not validate the example I have provided above (being a uuid instead of guide)?

**Comment by martin-shields-sage** [comment]
Would you suggest that we add a new format validator to the list based on https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/Validation/JsonSchemaValidator.cs#L28?

**Comment by RicoSuter** [comment]
> Would you suggest that we add a new format validator to the list based on

Yes. Can you create a PR?

**Comment by martin-shields-sage** [comment]
> > Would you suggest that we add a new format validator to the list based on
> 
> Yes. Can you create a PR?

Sure.
