### ISSUE TITLE
JsonSchemaGenerator generate schema unexpectedly!!!Why not obay the DataContract?

### ISSUE THREAD

**Issue by mokeyish** [RicoSuter/NJsonSchema#1328]
https://github.com/RicoSuter/NJsonSchema/blob/d8f5302ed5315167c361358735a90718de7abcd0/src/NJsonSchema/Generation/JsonSchemaGenerator.cs#L901

JsonSchemaGenerator generate schema unexpectedly!!!Why not obay the DataContract?

Here is my case code:
```c#

[DataContract]
class A {
     [IgnoreDataMember]
     public string MyField{get => _myField;
     set {
            // Do some stuff, excep for deserializing.
            _myField = value;
           }
    } 

     [DataMember(Name="MyField")]
     [Display(Name="My Field", Description="......")]
     private string _myField;
}
```

**NJsonSchema** cannot gernerate property `MyField` for` class A`;

**Comment by RicoSuter** [comment]
Can you create a PR with a test covering this misbehavior and also covering regular serialization/deserialization?
