### ISSUE TITLE
Question about Polymorphism support with System.Text.Json

### ISSUE THREAD

**Issue by bzuillsmith** [RicoSuter/NJsonSchema#1343]
The [documentation on inheritance](https://github.com/RicoSuter/NJsonSchema/wiki/Inheritance) assumes we are using Json.net. Is there any support for this using the System.Text.Json serializer by Microsoft? It's not clear to me if NSwag can use the latter, and if so, how to make it work.

**Comment by bzuillsmith** [comment]
Figured it out. Thanks

**Comment by RicoSuter** [comment]
A sample with converters (copy them) can be found here: 
https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema.Tests/Generation/SystemTextJson/SystemTextJsonInheritanceTests.cs
