### ISSUE TITLE
CS0117 'JsonSchema' does not contain a definition for 'FromTypeAsync'

### ISSUE THREAD

**Issue by vladik-hbinov** [RicoSuter/NJsonSchema#1379]
Trying to use the JSON schema generator using the example in the Readme.
Getting an error saying CS0117 'JsonSchema' does not contain a definition for 'FromTypeAsync', what am I missing?
I see no FromTypeAsync in the repo other than in the Readme and a test that is commented out.

**Comment by RicoSuter** [comment]
It has been changed to FromType (non async), updated the docs.
