### ISSUE TITLE
What is the correct behavior for nullable strings?

### ISSUE THREAD

**Issue by MartinWickman** [RicoSuter/NJsonSchema#1380]
I'm getting an exception when using the generated C# client with a string property that is set to `null`. 

 `Newtonsoft.Json.JsonSerializationException: Required property 'email' expects a non-null value.`

The relevant openapi snippet looks like this:

```
"person": {
  "type": "object",
  "properties": {
    //...
    "email": {
        "type": "string",  
                    <--- nullable: true is not set for this property
    },
}
```

The email property in the generated C# client looks like this (with `NSwag.CodeGeneration.CSharp`, version `13.11.3`):
```
[Newtonsoft.Json.JsonProperty("email", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
public string? Email { get; set; }= default!;
```

I am a bit confused here because I [reported this](https://github.com/Azure/azure-functions-openapi-extension/issues/133#issuecomment-864630511) as a potential bug in the client lib which generates the swagger spec. But [according to the author](https://github.com/Azure/azure-functions-openapi-extension/issues/133#issuecomment-864630511) of the lib:

> The `string` property itself allows nullable by default.

If that's correct, then the generated code is wrong?

If I manually change it to `AllowNull` it works (of course). 

I have `GenerateNullableReferenceTypes` to `true` by the way. Not sure if this is relevant though.

**Comment by RicoSuter** [comment]
JSON Schema and OpenAPI nullability is different - with JSON Schema "null" is a special type and with OpenAPI nullability has it's own property "nullable" on properties... because "nullable" is not set to true... if you look at this page, nullable is false by default: 
https://swagger.io/docs/specification/data-models/data-types/

**Comment by MartinWickman** [comment]
Yes that’s true, thanks for clearing that up!

So then it’s the openapi library I’m using that’s generating incorrect swagger: `string? Foo` properties don’t generate `nullable: true` as I would expect. Closing this issue.
