### ISSUE TITLE
Why are the Releases not in sync with what's published to NuGet?

### ISSUE THREAD

**Issue by IanKemp** [RicoSuter/NJsonSchema#1438]
The last time https://github.com/RicoSuter/NJsonSchema/releases was updated was over 2 years ago for version 10.0.4, but the NuGet version is currently at 10.5.2. Since Releases is the first thing I look at when checking a repo to determine if it has been updated recently (which influences whether I will use the code from said repo), on first glance it appears as if this project hasn't released anything in over 2 years, which is obviously not a great first impression. The fact that the last Released version is so different from the latest NuGet version is also confusing.

If you don't mind sharing, what are the reason(s) for no longer keeping Releases updated?

**Comment by RicoSuter** [comment]
I agree, this is not good. As there are only nugets we do not really need github releases and creating them was just not migrated when we moved to Azure DevOps CI pipelines... 

@lahma is working on moving this to Nuke and GitHub actions then we can also create releases again.

**Comment by lahma** [comment]
After the main PR lands I think we can investigate automatic publish + GH release creation based on pushed tag.

**Comment by IanKemp** [comment]
Glad to know that you are addressing this. 👍 Should I close this item since that is the case, or would it be helpful/useful to keep this open as a reminder until everything's sorted on your ends?

**Comment by lahma** [comment]
I think this could be a good reminder. If Rico is willing to make a jump of faith at some point and give me collaborator rights to repo I could retroactively create missing tags, push them and sync releases manually.

**Comment by IanKemp** [comment]
Then I'll leave this open and will celebrate with you when you mark it as implemented by closing it!

**Comment by RicoSuter** [comment]
@lahma sent you an invite for NJsonSchema & NSwag... 
let's update these two to Nuke CI and CD (NuGet push and releases)...
I'm also working on some refactorings/improvements we can then release as new major updates (NJS 11 & NSwag 14)

**Comment by lahma** [comment]
Great thank you! I'll work on enabling on following workflow:

* on push to main/master -> if no tag push to myget
* on push to main/master with tag"vXX.YY.ZZ" create packages with that given version and push to NuGet

I'll also add the currently missing tags following the "v*" format and publish missing releases. Creating the tag and triggering push to NuGet brings us quite close to easy releases as with tag it's easy to create the GitHub release and they now also support automatic release notes generation as preview feature.

**Comment by lahma** [comment]
I've pushed the missing vXXX tags and created release notes using the release note generator for 10.5 and 10.4 so far.

![image](https://user-images.githubusercontent.com/171892/142897067-b0de5b3c-8c48-455a-af7e-4d2346f1e996.png)

I guess we can close this issue now?
