### ISSUE TITLE
Update wiki to indicate how to use System.Text.Json instead of Newtonsoft.Json

### ISSUE THREAD

**Issue by IanKemp** [RicoSuter/NJsonSchema#1439]
https://github.com/RicoSuter/NJsonSchema/wiki/JsonSchemaGenerator links to #1014 which is closed. That wiki page should therefore be updated to show how to use STJ instead of Json.NET when generating schemas.

**Comment by RicoSuter** [comment]
https://github.com/RicoSuter/NJsonSchema/wiki/JsonSchemaGenerator#systemtextjson-vs-newtonsoftjson
