### ISSUE TITLE
Help needed with resolving references in NJsonSchema.Jsonchema.FromFileAsync

### ISSUE THREAD

**Issue by eekodeerder** [RicoSuter/NJsonSchema#1493]
I can successfully resolve references to JSON schema definitions used in an external file using the JSchemaPreloadedResolver when loading a JSchema from a root schema, where the reference points to a schema definition which is "located" at a valid (non-http(s)) Url but the file name (document path) has to be derived from the root document path and the schema name.

However, I am a bit daft trying to figure out how to locate the files related to a reference using a ReferenceResolverFactory.  It also seems as if $id is ignored.

I have a file VersionResource.json containing this:
{
  "$schema": "http://json-schema.org/draft/2019-09/schema#",
  "id": "sm.dataelement:/schemas/VersionResource",
  "allOf": [ { "$ref": "sm.dataelement:/schemas/Resource" } ],
  "type": "object",
  "properties": {
    "isVersionOf": {
      "type": "string",
      "format": "uri"
    },
    "modified": {
      "type": "string",
      "format": "date-time"
    },
    "versionId": { "type": "string" },
    "resource": { "$ref": "sm.dataelement:/schemas/Resource" }
  },
  "required": [ "isVersionOf", "modified" ]
}

and a Resource.json file in the same folder containing:
{
  "$schema": "http://json-schema.org/draft/2019-09/schema#",
  "$id": "sm.dataelement:/schemas/Resource",
  "type": "object",
  "properties": {
    "@id": {
      "type": "string",
      "format": "uri"
    },
    "@type": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "displayName": { "type": "string" }
  },
  "required": [ "@id" ]
}
.
With the JSchemaPreloadedResolver I basically Add all the .json files in the folder and then register a BaseUri with the file name without extension to the BaseUri. 
Do I need to implement my own reference resolver, or my own JsonSchemaAppender or my own TypeNameGenerator?   I am struggling to figure out exactly how these classes operate together.

**Comment by eekodeerder** [comment]
I figured out that I have to implement my own ReferenceResolver.  Thank you.

**Comment by jsb04** [comment]
@eekodeerder  are you able to provide an example please?
I have a schema with a lot of "$ref": "file://somepath/status.json"
I tried moving all of the schema files into one directory and updating the $ref in them accordingly.   Then I start with:
JsonSchema.FromFileAsync("message.json")
but I get a lot of "Could not resolve the JSON path" exception even though the files mentioned in the exception messages do exist.   
Would appreciated any help on how to use the resolver classes.

**Comment by eekodeerder** [comment]
I did this quite a while ago.  Will have to figure out what exactly I did.
