### ISSUE TITLE
JsonSchema.Generate<MyType>() not using xml documentation file from NuGet packages I use

### ISSUE THREAD

**Issue by egorlw26** [RicoSuter/NJsonSchema#1503]
So I have some class with the field of some class A that comes from nuGet package. Class A has his fields documented via `///` summary, xml documentation file is generated and packed together with nuget package. For some reason in generated schema I don't see those comments as the descriptions.

Correct if I need to set something up or if the same issue thread already exists. Thank you.

**Comment by RicoSuter** [comment]
Ref https://github.com/RicoSuter/Namotion.Reflection/issues/33
