### ISSUE TITLE
Generated C# DateFormatConverter for System.Text.Json does not use full name for JsonException

### ISSUE THREAD

**Issue by pvaillant** [RicoSuter/NJsonSchema#1515]
If you generate a C# client with a model that has a property with type: string and format: date, and are using JsonLibrary SystemTextJson then the generated client fails to compile with the following error:

`error CS0246: The type or namespace name 'JsonException' could not be found`

The issue is here; the generated DateFormatConverter does not specify the full name for JsonException.
https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.CSharp/Templates/DateFormatConverter.liquid#L10

`throw new JsonException("Unexpected JsonTokenType.Null");`

This code (PR #1490) comes from issue #1486. In the issue, the proposed code has the correct full name:

`throw new System.Text.Json.JsonException("Unexpected JsonTokenType.Null");`

So it seems to just have been missed in the PR.

I'm happy to create a PR for the fix if that's helpful.

**Comment by pvaillant** [comment]
And in case anyone else is having the same issue and it using .Net 6, you can work around it with `global using System.Text.Json;`

**Comment by AroglDarthu** [comment]
Good catch! Seems to have been fixed now by https://github.com/RicoSuter/NJsonSchema/pull/1505
