### ISSUE TITLE
Backwards compatability break 

### ISSUE THREAD

**Issue by drinehim** [RicoSuter/NJsonSchema#1519]
Version 10.7.1 introduced a breaking change to the `JsonSchemaValidator` class in a patch (non-breaking) version update. It replaced the constructor `public JsonSchemaValidator(params IFormatValidator[] customValidators)` with `public JsonSchemaValidator(JsonSchemaValidatorSettings settings)`. This has broken a lot of our integrations with packages like Confluent.SchemaRegistry.Serdes.Json.

**Comment by bruegth** [comment]
@RicoSuter @drinehim #1520 solves only constructor not the validate methods:

```
System.MissingMethodException: Method not found: 
System.Collections.Generic.ICollection`1<NJsonSchema.Validation.ValidationError>NJsonSchema.JsonSchema.Validate(System.String, NJsonSchema.Validation.FormatValidators.IFormatValidator[])'.
```

Before 10.7.1:
public ICollection<ValidationError> Validate(JToken token, params IFormatValidator[] customValidators);
After:
public ICollection<ValidationError> Validate(string jsonData, JsonSchemaValidatorSettings settings = null);


`Schema.Validate(strJson)` will fail at runtime if a newer package version is included somewhere else.

**Comment by drinehim** [comment]
Thanks for pointing that out @bruegth just created PR #1557

**Comment by RicoSuter** [comment]
Just ensure you use the same versions,
current releasable version will be v11 and it will anyway breaking.
