### ISSUE TITLE
Create NJsonSchema.Attributes package

### ISSUE THREAD

**Issue by trejjam** [RicoSuter/NJsonSchema#1628]
Hi,
are you open to extracting `NJsonSchema/Attributes` into a standalone package?

My motivation is that these attributes are used on the Domain/Contract level and most of your solution depends on these. That is fine by itself, but `NJsonSchema` has its dependencies like `Newtonsoft.Json` which we would like to push out of our codebase.

I know that `Newtonsoft` is heavily used in the library and I am not asking to remove it :) I am ok to use it in places where it makes sense.

If you are open to it, I can prepare a PR for it

**Comment by RicoSuter** [comment]
I think that's a good idea, NSwag also has this with the NSwag.Annotations package so maybe we should also call it NJsonSchema.Annotations

**Comment by RicoSuter** [comment]
v11.0.0-preview006
