### ISSUE TITLE
Prevent reference generation for selected complex class properties

### ISSUE THREAD

**Issue by nautnatic** [RicoSuter/NJsonSchema#1658]
Hi,
I'm trying to generate a JSON schema for a C# class. While I generally want to generate references for complex properties (type class), I have some classes that are only used as a property once. Therefore, I don't want to create a separate model in the JSON schema, but nest it within the owning class to decrease complexity.

Here a small example:

### C# classes

```C#
public class BaseClass
{
    public NestedClass NestedProperty { get; set; }
}

public class NestedClass
{
    public string Property1 { get; set; }
}
```

### Actually generated JSON schema

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "BaseClass",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "nestedProperty": {
      "$ref": "#/definitions/NestedClass"
    }
  },
  "definitions": {
    "NestedClass": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "property1": {
          "type": "string"
        }
      }
    }
  }
}
```

### Desired JSON schema

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "BaseClass",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "nestedProperty": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "property1": {
          "type": "string"
        }
      }
    }
  }
}
```

Is there some way to achieve this in NJsonSchema?
Happy about all suggestions. :)

**Comment by emillno** [comment]
I think the solution to what you're trying to achieve can be found in this issue: https://github.com/RicoSuter/NJsonSchema/issues/889

**Comment by nautnatic** [comment]
Yeah it sounds like the same issue. Will close this issue.
