### ISSUE TITLE
 System.MissingMethodException: Method not found: 'Void NJsonSchema.JsonSchema.set_Type(NJsonSchema.JsonObjectType)

### ISSUE THREAD

**Issue by vasiles** [RicoSuter/NJsonSchema#1679]
Hi, I have a controller and generate the spec from it with OperationProcessor. **With v13.20, everything was fine**.
I add an operation like this:

..
 operation.Parameters.Add(new OpenApiParameter
 {
     Name = "name",
     Kind = OpenApiParameterKind.Header,
     Schema = new NJsonSchema.JsonSchema { Type = NJsonSchema.JsonObjectType.String },
     Description = "description",
     IsRequired = false,
 });
..

**After upgrading to v14.0.3, I get the following error.**
```
NSwag command line tool for .NET Core Net60, toolchain v14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))
  Visit http://NSwag.org for more information.
  NSwag bin directory: C:\Users\user\.nuget\packages\nswag.msbuild\14.0.3\tools\Net60

  Executing file '.\.swagger\AspNetCoreToOpenApiDocument.nswag' with variables 'ProjectPath=C:\Service.csproj,Output=C:\Service\../ApiSpecifications/Specification.json,Configuration=Debug,runtime=Net60'...
  Launcher directory: C:\Users\user\.nuget\packages\nswag.msbuild\14.0.3\tools\Net60

---> System.MissingMethodException: Method not found: 'Void NJsonSchema.JsonSchema.set_Type(NJsonSchema.JsonObjectType)'.
     at MyCompany.NSwag.AddChannelHeaderParametersFilter.Process(OperationProcessorContext context)
     at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.RunOperationProcessors(OpenApiDocument document, ApiDescription apiDescription, Type controllerType, MethodInfo methodInfo, OpenApiOperationDescription operationDescription, List`1 allOperations, OpenApiDocumentGenerator generator, OpenApiSchemaResolver schemaResolver)
....
```
Any idea what is going on @RicoSuter 

thnx

**Comment by gitlsl** [comment]
same issue

**Comment by ZhangMichaelElekta** [comment]
I meet the same problem

**Comment by lahma** [comment]
> at MyCompany.NSwag.AddChannelHeaderParametersFilter.Process(OperationProcessorContext context)

Seems that the code throwing error is *your* code. You are probably referencing an old version of NSwag/NJsonSchema somewhere.
