### ISSUE TITLE
Using the generic type 'JsonInheritanceConverter<TBase>' requires 1 type argument

### ISSUE THREAD

**Issue by kemmis** [RicoSuter/NJsonSchema#1686]
I'm using the JsonInheritanceConverter attribute on classes as described in the wiki [here](https://github.com/RicoSuter/NJsonSchema/wiki/Inheritance#declare-inheritance).

After upgrading from NJsonSchema 10.9.0 to 11.0.0 this syntax no longer works:
```
[JsonConverter(typeof(JsonInheritanceConverter), "discriminator")]
public class MyClass {}
```
And I get this error at build time: `Error	CS0305	Using the generic type 'JsonInheritanceConverter<TBase>' requires 1 type arguments`

Adding `<>` to the type like this appears to resolve my build issues:
```
[JsonConverter(typeof(JsonInheritanceConverter<>), "discriminator")]
public class MyClass {}
```
Is this the correct way to use JsonInheritanceConverter with the JsonConvert attribute now?

**Comment by RicoSuter** [comment]
The class has been moved to 
https://www.nuget.org/packages/NJsonSchema.NewtonsoftJson

(You’re referencing the system.text.json one [default])
