### ISSUE TITLE
Synchronous methods removed?

### ISSUE THREAD

**Issue by vector-man** [RicoSuter/NJsonSchema#334]
Hi. I was using an older version of NJsonSchema. When I updated through nuget to the latest release, it appears that the synchronous versions of several methods were removed (e.g.  FromFile). This, of course, broke my project. Without having to rewrite lots of my code, do the synchronous methods still exist somewhere?

**Comment by rsuter** [comment]
No, they have been removed... But i'm thinking about adding them as a fallback option (using `Task.Run(...).Result` internally)

**Comment by vector-man** [comment]
Okay. Thanks for confirming. I have decided to rewrite my code to allow async.

**Comment by rsuter** [comment]
See https://github.com/NJsonSchema/NJsonSchema/issues/333

**Comment by zinvob** [comment]
It would be nice if it was possible to make them available without using Task.Run internally. Task.Run will make a new thread, and use locks to wait for the result before it returns. That means it will consume more cpu and take more time.

**Comment by rsuter** [comment]
Task.Run does not create a new thread, it uses the thread pool. Just calling ToJsonAsync().Result is not possible because it can cause a dead lock (in dispatcher threaded Environments like WPF)

**Comment by zinvob** [comment]
Yes, it takes up a thread from the thread pool. And it will use locks to handle the blocking. This will create a good overhead in cpu usage when you don't want async processing.

**Comment by mj1856** [comment]
Sorry, just got here - but can you elaborate (or point at previous discussion) about why these methods are async in the first place?  Async makes sense when I/O is involved, but doesn't usually apply for things that occur strictly in memory.  `JsonSchema4.FromTypeAsync<T>` doesn't do any I/O, so I can't fathom why it is asynchronous.

**Comment by RSuter** [comment]
It reads XML documentation files (I/O)...

**Comment by mj1856** [comment]
Oh.  I didn't realize it was doing that.  I wonder why it needs to do that?

**Comment by RSuter** [comment]
https://github.com/RSuter/NJsonSchema/wiki/XML-Documentation

**Comment by mj1856** [comment]
Thanks.  That makes sense.  I'll have to be sure to enable XML documentation files in my project settings.  They're off by default for many project types.

**Comment by RSuter** [comment]
Yes, they are only read if available... otherwise you can mostly also use DescriptionAttributes...

**Comment by vinniep79** [comment]
I would cast a vote for having the synchronous methods returned.  Async doesn't make sense for my scenario.

**Comment by RicoSuter** [comment]
Method is now sync:
https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/JsonSchema.cs#L93
