### ISSUE TITLE
JsonSchemaGenerator.GenerateAsyc() never returns

### ISSUE THREAD

**Issue by vinaysharma77** [RicoSuter/NJsonSchema#346]
I have this code which works perfectly fine when I run it from my unit test.. but when I try it over IIS through postman or any other client the "schemaGen.GenerateAsync(sourceType).Result" never returns a response back.. sourceType is the Type of my POCO.

        private JsonSchema4 GenerateSchema(Type sourceType)
        {
            NJsonSchema.Generation.JsonSchemaGenerator schemaGen = _schemaGenerator.Value;
            var readSchema = schemaGen.GenerateAsync(sourceType).Result;
            return readSchema;
        }

As per the response to one more question on the blog, I tried this as well but no luck:

            var readSchema = schemaGen.GenerateAsync(sourceType).GetAwaiter().GetResult();

This could result into a show stopper if unable to get a resolution on this.. Any quick help/guidance on this will be greatly appreciated.

PS: I tried upgrading the NJsonSchema to the latest release (8.14.6289.34345). Still no luck

Thanks,
Vins

**Comment by moh-hassan** [comment]
Hi vinaysharma,

I modified your code to use async/await to avoid thread blocking and it's working fine in IIS ASP.Net Application..
 
       private async Task<JsonSchema4> GenerateSchema(Type sourceType)
        {
            NJsonSchema.Generation.JsonSchemaGenerator schemaGen =
                                  new JsonSchemaGenerator(new JsonSchemaGeneratorSettings());   
                                //_schemaGenerator.Value;
            var readSchema = await schemaGen.GenerateAsync(sourceType).ConfigureAwait(false);
            return readSchema;
        }
 
 
Ii called it in a webform page and returning valid result:
 
       protected async void Button2_Click(object sender, EventArgs e)
        {
            var schema= await GenerateSchema(typeof(Person));
            Label1.Text =  schema.ToJson();
        }

The result Schema:

         {
		"$schema": "http://json-schema.org/draft-04/schema#",
		"type": "object",
		"title": "Person",
		"additionalProperties": false,
		"properties": {
			"id": {
				"type": "integer",
				"format": "int32"
			},
			"name": {
				"type": ["null", "string"]
			}
		}
	}

The POCO Class:
	
	   class Person
		{
                    public int id { get; set; }
                   public string name { get; set; }
		}

Best Regards,

**Comment by rsuter** [comment]
See https://github.com/NJsonSchema/NJsonSchema/issues/333

**Comment by RicoSuter** [comment]
Method is now sync:
https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/JsonSchema.cs#L93
