### ISSUE TITLE
Which SchemaType?

### ISSUE THREAD

**Issue by brgrz** [RicoSuter/NJsonSchema#592]
Our code used to use NullHandling.Swagger as null handling option. I guess the most painless way to switch to new version is to replace 

`settings.NullHandling = NullHandling.Swagger;`

with

`setting.SchemaType = SchemaType.Swagger2;`

But what about the other two options? I'm aware the Open API 3 is replacing the Swagger spec but what about JSON Schema v4? If we were to rewrite our schemas, which type should we go with?

**Comment by RSuter** [comment]
Yes, this property has been generalized to SchemaType, just use `SchemaType.Swagger2` if the schema is used within a SwaggerDocument

**Comment by RSuter** [comment]
SchemaType.OpenApi3 is not yet fully implemented...
