### ISSUE TITLE
C# CodeGeneration: How to avoid anonymous types?

### ISSUE THREAD

**Issue by NickCiao** [RicoSuter/NJsonSchema#602]
I'm trying to avoid auto-generating C# classes with the `Anonymous` name.  As far as I can tell my JSON schema is labeling everything, here's what my JSON-schema looks like:

I have 2 files, a file of reusable definitions that looks like this:
```
definition.json

{
    "$schema": "http://json-schema.org/draft-04/schema#",

    "definitions": {
        "childItem": {
            "type": "object",
            "properties": {
                "someField": { "$ref": "#/definitions/someField" }
            }
        },
        "parentArray": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/childItem"
            }
        },
        "someField": {
            "type": "string"
        }
    }
}
```

And the schema file for my object:
```
ObjectWithUnwantedAnonymousChildItems.json

{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "AnonIssue",
    "type": "object",
    "properties": {
        "Values": { "$ref": "definition.json#/definitions/parentArray" }
    }
}
```

When I generate the C# class from my JSON schema files, `Values` is typed as:
`System.Collections.ObjectModel.ObservableCollection<Anonymous>`

Is there a way to get around this and have `Values` typed as:
`System.Collections.ObjectModel.ObservableCollection<childItem>`?

**Comment by soulomoon** [comment]
+1

**Comment by RSuter** [comment]
The latest version uses the "title" property as class name fallback...

**Comment by RSuter** [comment]
Ref https://github.com/RSuter/NJsonSchema/issues/607
