### ISSUE TITLE
MultipleOf not used in CodeGeneration.CSharp

### ISSUE THREAD

**Issue by basilfx** [RicoSuter/NJsonSchema#671]
I noticed that MultipleOf on number properties is not used/considered when generating classes from JSON Schemas. It's an useful feature to ensure data truncation is noticed before data is serialized.

Is there a way to use it? I tried to use templates to add a custom attribute, but MultipleOf is not exposed in `PropertyModel `.

Using 9.10.42.0.

**Comment by RSuter** [comment]
What should this generate?

**Comment by basilfx** [comment]
I came up with the following two possibilities that don't depend on external dependencies: https://gist.github.com/basilfx/22a6042ecb9f19da29f8b786e0658cfd.
