### ISSUE TITLE
Conditional FlattenHierarchy process

### ISSUE THREAD

**Issue by vpaulino** [RicoSuter/NJsonSchema#677]
Hi there, 

 I need to maintain my object model hierarchy for some types and for others the hiearchy can be flatten. A possible solution would be similiar to the solution of the excludedTypeNames but to Types to be flatten based on a rule matching pattern. 
The purpose would be to have a more dynamic process to decide wich types would be flatten instead of the current approach that is global to all types. This approach allows a more dynamic flat hiearchy process, instead of the  property FlattenInheritanceHierarchy from JsonSchemaGeneratorSettings.
A possible implementation would be: 
JsonSchemaGeneratorSettings would have a rules collection, and each rule specify what actions could be done to what objects if they match . The object Rule would have three properties :

Rule {
+Name:string
+Action:ActionOptions 
+Predicate:Func<Type, bool>          
}
[Flags]
ActionOptions : {
  Flat,
  Exclude,
}

This makes sense ? Is it possible to solve this problem at the current version of NSJonSchema ? If not, feel free to ask some questions about this solution.

**Comment by RSuter** [comment]
Good idea, what is the predicate used for? It would be great if we had a solution which does not require code extensions (i.e. settings which can be serialized). Is that possible or not flexible enough?

**Comment by vpaulino** [comment]
Great news! :)
The predicate would define what is the condition that must be match in order to one of the ActionsEnum be executed:

Rule doNotFlatAll= new Rule();
doNotFlatAll.Predicate = (type)=> type.Namespace.contains(“MyModel.”);
doNotFlatAll.Action=ActionEnum.Flat;

All types where the namespace begins by MyModel would not be flatten !

**Comment by RSuter** [comment]
If you need a predicate, then we should directly implement an extension point which also supports changing the action, e.g.

    Func<Type, Action>

but wouldn't be something like a string-action-dictionary be enough (this would be serializable), e.g.

    { { "MyModel.*", Action.Flat }, { "MyModel.Foo.*", Action.Ignore } }

**Comment by vpaulino** [comment]
The [Predicate ](https://msdn.microsoft.com/en-us/library/bfcke1bz(v=vs.110).aspx) by definition returns a bool value, thtat's one of the reasons why I proposed the Predicate that way. Returning the bool I think it give us more flexibility to interpret the result as we want, as true or as false and it can be use on any of the existing Linq methods available on the .NET Framework. 

A look into some code changes that would be made, the method GenerateInheritanceAsync of class JsonSchemaGenerator we can find this:

```
if (Settings.FlattenInheritanceHierarchy) 
{
 // code to deal with it 
}
```

and then, a few lines of code later on there is : 
  
```
if (Settings.FlattenInheritanceHierarchy && Settings.GenerateAbstractProperties)
 {
    // more lines of code here 
  }
```

with this approach this code would look like this: 

```
if(Settings.Rules.Where((rule)=>rule.Action == Action.Flat && rule.Predicate(type))
{
 // the existing code goes where
}
```
and the other piece of code would look like this, assuming that ActionEnum would support Flag enumeration: 

```
if (Settings.Rules.Where((rule)=>rule.Action == Action.Flat | Action.GenerateAbstractProperties && rule.Predicate(type))
 {
    // more lines of code here 
  }
```

The same applies to the ExcludedTypeNames property in the settings. 
where we have the code: 

`if(Settings,ExcludedTypeNames?.Contains(baseType.FullName)){}`

we could let the developer decide the criteria wich the type would be excluded. 

The developer would configure the Rule like this:
 ```
Rule toFlat= new Rule();
toFlat.Predicate = (type)=> type.FullName.Contains("MyModel.Foo.*");
toFlat.Action=ActionEnum.Ignore;
```

and the predicate would be used like this:

`if(Settings.Rules.Where((rule)=> rule.Action == Action.Ignore && rule.Predicate(baseType))
{
}`

**Comment by RSuter** [comment]
FYI: Added JsonSchemaFlattenAttribute: https://github.com/RSuter/NJsonSchema/commit/c1484a03e864fe086be5fb99a42450196bb1d4ee

See wiki: https://github.com/RSuter/NJsonSchema/wiki/Inheritance#flatten-inheritance-hierarchy
