### ISSUE TITLE
Add the ability to put imported clientBaseClass on top of the generated typescript file

### ISSUE THREAD

**Issue by jeremyVignelles** [RicoSuter/NJsonSchema#779]
In NSwag, when I try to generate a Typescript client, I can set a clientBaseClass and import a file in the generated typescript client.

However, the included content gets written at the bottom of the file, which results in 

> TS2449: Class 'BaseClass' used before its declaration.

**Comment by RSuter** [comment]
Really strange, the ClientBaseClass should be passed in the baseClasses parameter: 

![image](https://user-images.githubusercontent.com/2603405/45814188-26cfab00-bcd5-11e8-8d83-1be6a515573f.png)

And this parameter should be added on top, see: 
https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.TypeScript/TypeScriptExtensionCode.cs#L41

**Comment by jeremyVignelles** [comment]
For reference, here is the extension code (some comments containing build instructions were removed to keep it simple):

```
// Imported class for NSwag code generation to use cookies in http fetch requests
// Temporary solution that should be superseded by https://github.com/RSuter/NSwag/issues/734

// [...]

// Use NSwag Studio with the .nswag to generate the code
// Find this piece of code at the bottom of the file, and move it to the top

export class UseHttpCookiesForApi {
    protected transformOptions(options: RequestInit): Promise<RequestInit> {
        options.credentials = 'same-origin';
        return Promise.resolve(options);
    }
}
```

**Comment by RSuter** [comment]
So your `clientBaseClass` setting is set to `UseHttpCookiesForApi` and `UseHttpCookiesForApi` is still rendered at the bottom of the file?

**Comment by jeremyVignelles** [comment]
Here is a repro repo : https://github.com/jeremyVignelles/TestNSwagNetCoreApp
The fact that the text "class" is included in the comment above my class seems to bug the parser.
Also, if I remove the comment, my base class code is removed from the bottom, but not included at the top...

**Comment by RSuter** [comment]
If i remove the comment, the class is generated at the top...

**Comment by jeremyVignelles** [comment]
Right, I was putting UseHttpCookiesForApi in both clientBaseClass and extendedClasses...

**Comment by RSuter** [comment]
I've added a PR which would fix your problem. Not sure however if it breaks someone else...

**Comment by danielwinkler** [comment]
> The fact that the text "class" is included in the comment above my class seems to bug the parser.

That did it for me!
