### ISSUE TITLE
ShouldSerialize on Nullable Enum leads to Null Reference Exception

### ISSUE THREAD

**Issue by ddrdoubled** [RicoSuter/NJsonSchema#929]
public class Party {

public SomeEnum? EnumValue {get; set;}

public bool ShouldSerializeEnumValue() 
{
return this.EnumValue.HasValue;
}
}

**Comment by RSuter** [comment]
At schema generation time there will be no instance of Party (i.e. everything is done via reflection/metadata) that's why it internally throws an NPE - there is no way to avoid this. 

Added test...

**Comment by ddrdoubled** [comment]
By looking at it deeply, it is an JSON.NET issue, the delegate created in the DefaultContractResolver under CreateShouldSerializeTest() throws this null exception, probably due to wrong Nullable type handling like:
https://stackoverflow.com/questions/6026824/detecting-a-nullable-type-via-reflection

**Comment by ddrdoubled** [comment]
Please see discussion here https://github.com/JamesNK/Newtonsoft.Json/issues/2017
if this is true, then your whole call of ShouldSerialize doesn't make much sense in GeneratePropertiesAsync
or am I wrong?

**Comment by ddrdoubled** [comment]
Sorry to ask, but why do you iterate through all properties, even when they are marked as [JsonIgnore]. With the way it is implemented there is ShouldSerialize method possible. For what do you need properties which are marked with JsonIgnore Attribute?

**Comment by RSuter** [comment]
Is this actually blocking someone? i.e. is the schema generator failing because of this? There will be no way to make this work as during schema generation time there will be no "this"/instance and this method will always throw an exception...

**Comment by ddrdoubled** [comment]
Fine for me but then you should throw the whole idea of support of "ShouldSerialize" away, right?

**Comment by ddrdoubled** [comment]
I need "ShouldSerialize" for XmlSerialization of Nullable Types, where it is the only decent possibility to serialize Nullable without <xsi: nil for null values. Maybe a go the Specified route because it is not used by Json.NET where ShouldSerialize is

**Comment by ddrdoubled** [comment]
see here: https://stackoverflow.com/questions/244953/serialize-a-nullable-int?rq=1

**Comment by ddrdoubled** [comment]
I would like to help: I think this stuff in the JsonSchemaGenerator does not look decent:
`try`
`{`
`shouldSerialize = property.ShouldSerialize?.Invoke(null) != false;`
`}`
`catch`
`{`
`shouldSerialize = true;`
`}`

I think we both agree, that supporting ShouldSerialize doesn't make sense without an instance of the type. So either we create an instance or we leave the whole part out, or not?

**Comment by RicoSuter** [comment]
The idea is that we support the method if it does not need an instance (i.e. the logic is static), otherwise we use shouldSerialize = true

Creating an instance is not an option as first we cannot do this reliably and it would only reflect the method for this particular instance not all possible instances... 

So in order to not break anything we will leave this as is.
