### ISSUE TITLE
JsonPatchDocument

### ISSUE THREAD

**Issue by ddrdoubled** [RicoSuter/NJsonSchema#935]
Seems out of the box JsonPatchDocument<> is not supported. Is there a way to make it work for a patch operation like:

[HttpPatch("{id}")]
        public IActionResult Patch(long id, [FromBody]JsonPatchDocument<string> patches)
        {
            return this.StatusCode(StatusCodes.Status202Accepted);
        }

**Comment by RicoSuter** [comment]
So the schema for jsonpatchdocument is wrong? You could overwrite the schema with a custom type mapper...

**Comment by ddrdoubled** [comment]
same issue with this ShouldSerialize due to wrong Exception catch.
