### ISSUE TITLE
NJsonSchema 10.0.1 not compability with NSwag 12.3.0

### ISSUE THREAD

**Issue by lukapor** [RicoSuter/NJsonSchema#974]
I updated asp net core web application with new NSwag.AspNetCore, NSwag.MSBuild to version 12.3.0 and NJsonSchema to 10.0.1.

I got error when web server started. Here is stack trace
Unhandled Exception: System.TypeLoadException: Could not load type 'NJsonSchema.ReferenceTypeNullHandling' from assembly 'NJsonSchema, Version=10.0.1.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102'.
   at LoopWebApi.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Shared.WebServiceHelper.WebServiceHelper.GetHost[Startup](String pathToContentRoot, IConfiguration configuration) in C:\Marg\4O_Backend\src\Lib.Shared\WebServiceHelper\WebServiceHelper.cs:line 154
   at LoopWebApi.Program.Main(String[] args) in C:\Marg\4O_Backend\src\apps\LoopWebApi\Program.cs:line 32
Services initialized.

I revert NJsonSchema to version 9.14.1, now works.

**Comment by RicoSuter** [comment]
Yep v10.0.1 will be used in v13 which is released soon

**Comment by OpusKrokus** [comment]
Hi  @RicoSuter,  
You mentioned that it will be released "soon".  Do you have a rough timeline?  If it is very long at all, have you considered publishing a prerelease?

**Comment by RicoSuter** [comment]
Next days... i wonder if i should do the big rename in this release (Swagger* => OpenApi* classes)

**Comment by RicoSuter** [comment]
I've setup a preview nuget feed for NSwag: https://www.myget.org/feed/Packages/nswag
But because v13 is till in a PR (https://github.com/RicoSuter/NSwag/pull/2178) it is not available as preview yet - but will merge tomorrow then you'll have at least a preview for now...

**Comment by OpusKrokus** [comment]
> Next days... i wonder if i should do the big rename in this release (Swagger* => OpenApi* classes)

My personal opinion is that it would be a good idea to make that change since there is a major version number change with it.  

Because of the nature of the error thrown, I thought there were some hidden dependencies and was trying DLL redirects and such.  It ended up costing about half a day.  Whether you make the change or not, I would also recommend updating the current NJasonSchema package (10.#) with a dependency on NSwag >= v13.  Maybe also put a note on the project page.  It would save people some grief.

**Comment by OpusKrokus** [comment]
> I've setup a preview nuget feed for NSwag: https://www.myget.org/feed/Packages/nswag
> But because v13 is still in a PR ([RicoSuter/NSwag#2178](https://github.com/RicoSuter/NSwag/pull/2178)) it is not available as preview yet - but will merge tomorrow then you'll have at least a preview for now...

Thanks so much! I really appreciate this software and I know it takes a lot of work to keep things going.  I was introduced to Swashbuckler, but switched to NSwag as soon as I found out about it and never looked back.

**Comment by RicoSuter** [comment]
> I would also recommend updating the current NJasonSchema package (10.#) with a dependency on NSwag >= v13. 

What do you mean by that? NJsonSchema and NSwag are developed in tandem and NSwag v13 will be breaking also because of the upgrade to NJS v10 :-)

**Comment by RicoSuter** [comment]
NSwag v13 preview should be available soon.

**Comment by RicoSuter** [comment]
v13 is now available in the preview stream
