### ISSUE TITLE
Support for defining `patternProperties` on dictionary properties

### ISSUE THREAD

**Issue by Cisien** [RicoSuter/NJsonSchema#991]
I have a case where I'm using a dictionary to allow an arbitrary length object with user-defined key names. I need to perform additional validation on these key names but have not found a way to do it in the library currently.

I propose supporting the DataAnnotations RegularExpressionAttribute on dictionaries -- using the pattern provided to build the patternProperties schema value(s)
```cs
        [Required, RegularExpression(".*")]
        public Dictionary<string, string> People { get; set; }
```
This would generate the following schema:
```json
{
  "type": "object",
  "patternProperties": {
    ".*": { "type": "string" }
  },
  "additionalProperties": false
}
```

Reference: https://json-schema.org/understanding-json-schema/reference/object.html#pattern-properties

**Comment by RicoSuter** [comment]
Implement in JsonSchemaGenereator. GenerateDictionary and search for RegularExpressionAttribute in the source code for how to implement this...

**Comment by RicoSuter** [comment]
This test will break because currently we use this regex for the values: 

![image](https://user-images.githubusercontent.com/2603405/58960676-f323ab00-87a7-11e9-86f0-e1b70ce57b7c.png)

**Comment by Cisien** [comment]
In that case, it might make sense to use a custom attribute for setting this property in order to avoid a breaking change, or limiting the ability to validate values.

**Comment by RicoSuter** [comment]
I wonder what scenario makes more sense to support with the RegularExpressionAttribute here?

**Comment by RicoSuter** [comment]
https://github.com/RicoSuter/NJsonSchema/pull/995
