### ISSUE TITLE
Support for `min/maxProperties` on dictionary properties

### ISSUE THREAD

**Issue by Cisien** [RicoSuter/NJsonSchema#992]
I have a case where I need to constrain the minimum and maximum number of properties defined on an object in the JSON. 

I propose supporting the Min/Max length DataAnnotation attributes to configure these constraints in the resulting JSON

```cs
        [Required, MinLength(2), MaxLength(3)]
        public Dictionary<string, string> People { get; set; }
```
This would generate the following schema:
```json
{
  "type": "object",
  "minProperties": 2,
  "maxProperties": 3
}
```

Reference: https://json-schema.org/understanding-json-schema/reference/object.html#size

**Comment by RicoSuter** [comment]
Should be quite easy to implement in the JsonSchemaGenerator.GenerateDictiomary method

**Comment by RicoSuter** [comment]
https://github.com/RicoSuter/NJsonSchema/pull/995
