### ISSUE TITLE
AllowAdditionalProperties does not produce json schema accordingly

### ISSUE THREAD

**Issue by enrico-padovani** [RicoSuter/NJsonSchema#993]
Hi,

I'm trying to validate a complex json and I want to allow additional properties, so:

```
var schema = await JsonSchema4.FromTypeAsync<T>(new JsonSchemaGeneratorSettings { FlattenInheritanceHierarchy = true });
schema.AllowAdditionalProperties = true;
var schemaData = schema.ToJson();
```

I still got "additionalProperties": false in the generated json. Now I've hacked it like this in order to make it work:

`schemaData.Replace("\"additionalProperties\": false", "\"additionalProperties\": true");`

**Comment by RicoSuter** [comment]
schema.AllowAdditionalProperties = true;

only sets the property on the root schema not on all schemas, did you consider that?

**Comment by enrico-padovani** [comment]
I didn't know that, is there a way to set this property in order to be applied in the whole hierarchy?

**Comment by RicoSuter** [comment]
Are you looking for this new setting?

https://github.com/RicoSuter/NJsonSchema/pull/981

**Comment by enrico-padovani** [comment]
I'm using 9.13.37, not sure if can upgrade to 10.x. Is that something you could backport to 9.x?

**Comment by RicoSuter** [comment]
Are you using it with nswag?

**Comment by enrico-padovani** [comment]
Nope, just validating some json strings mapped to DTO classes

**Comment by RicoSuter** [comment]
Whats holding you back to use v10?

**Comment by enrico-padovani** [comment]
Since I'm on .net 4.6.2 I didn't want to add the dependency on Namotion.Reflection. For now I'll just use the replace trick. I'm closing this issue since it seems not present in the new version 10.x

**Comment by RicoSuter** [comment]
You can implement this recusively with a custom JsonReferenceVisitor
