### ISSUE TITLE
Understanding Flatten Inheritance with duplicate properties

### ISSUE THREAD

**Issue by lunchboxsushi** [RicoSuter/NJsonSchema#998]
I had a look at the inheritance documentation but I was unable to find a decent example with the following flow of logic. I need to hide the base class property and keep the child property, however the type is different only the name is the same.

*This is a specific issue when using* `FlattenInheritanceHierarchy = true`

For example

```C#
public class Person {
   public List<string> Mapping { get; set; }
}

// This will cause Error: "The JSON property 'Mapping' is defined multiple times on type Teacher"
public class Teacher: Person {
    public List<PersonMapping> Mapping { get; set; }
}

// Will be fine and use List<string> Mapping { get; set; }
public class Officer: Person {}
```

From the examples I've seen [JsonIgnoreAttribute] will be applied to every class that inherits 
from **Person** but I only need it to be applied on 1 or 2 inherited classes to use 

```C#
public List<PersonMapping> Mapping { get; set; }
``` 
and the others should still use 
```C#
public List<string> Mapping { get; set; }
```

Essentially I need a way to have a conditional JsonIgnoreAttirbute or a configuration for *FlattenInheritanceHierarchy* that will not use base properties if names match

**Comment by RicoSuter** [comment]
How does JsonIgnoreAttribute behave in the actual JSON serializer?

**Comment by lunchboxsushi** [comment]
I just have the default NewtonSoft.JSON library without any configraionts.

For example if I have 

```C#
public class Person {
    [JsonIgnore] // Added ignore
   public List<string> Mapping { get; set; }
}

// This will cause Error: "The JSON property 'Mapping' is defined multiple times on type Teacher"
public class Teacher: Person {
    public List<PersonMapping> Mapping { get; set; }
}

// will be missing Mapping property in the schema generation it should still be included
public class Officer: Person {}
```

**Comment by RicoSuter** [comment]
My question is how does the serializer treat JsonIgnore attributes? With or without inheritance?

**Comment by RicoSuter** [comment]
So to summarize you want an “overwrite” option?

**Comment by lunchboxsushi** [comment]
Yes an overwrite option would be ideal, I'm not sure if there's already a work around for this I've gone through different options in `JsonSchemaGeneratorSettings` but haven't found any options for it

**Comment by RicoSuter** [comment]
I dont think theres an easy workaround

**Comment by lunchboxsushi** [comment]
Would you be open to adding this functionality if I create a PR for this? if so would you prefer a new Property added `IgnoreInhertianceDuplicates` or `IgnoreInhertianceDuplicatesFromBase`. As an additional property for backwards compatibility ?
